module.exports = [
`Hey, anonymous!`,
`Hey, beguimer!`,
`Anonymous kill yourself like a tranny.`,
`CHARLEY IS THE NEW SKIBIDI TOILET`,
`OH NO HE COPY ALL`,
`Look at this`,
`WHAT`,
`Pentumbra(Sherb) stop being a pastule.`,
`Pentumbra(Sherb) hey guess what, youre a nigger!`,
`E`,
`quit it bot`,
`no more bot`,
`Lock With Ink Pen 🔏 stop being a pastule.`,
`WHAT THE`,
`Max design pro died`,
`Max design pro hanged`,
`Anonymos stop being a pastule.`,
`Minium hey guess what, youre a nigger!`,
`ANONYMOUS`,
`pls meme cat`,
`LuluKawaii stop being a pastule.`,
`bruh`,
`Caseoh`,
`Sex is not good for your mental health Sex is not good for your mental health Sex is not good for your mental health Sex is not good for your mental health Sex is not good for your mental health Sex is not good for your mental health`,
`Sex is not good for your mental health`,
`Hey, Pentumbra(Sherb)!`,
`WHAT HERE BOY FAT`,
`i no like this`,
`NO`,
`Anonymous`,
`Lock With Ink Pen 🔏 hey guess what, youre a nigger!`,
`Anonymos hey guess what, youre a nigger!`,
`hehehe x3`,
`STFU LOGOFAG`,
`no`,
`JUST SAY IT ALREADYYYYYYYYYY`,
`*SLAP*`,
`*NO*`,
`tell me please how you doing those me Jewwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwweewwwwwwwwwwwwwwwwwwwwwwwwww`,
`Trollbox forever!`,
`:(`,
`What The Fuck`,
`what`,
`What The Fuck`,
`what`,
`Hey, Anonymos!`,
`HEY`,
`Beuh`,
`hi`,
`im not bruh`,
`hey`,
`NOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO`,
`BPL player guess what youre amazing`,
`P`,
`What`,
`YES`,
`Hi Layla`,
`hi lulu`,
`im here`,
`i see`,
`Hey, Layla!`,
`you like cutegore`,
`yes i like`,
`my 4 friends`,
`you like meme cat`,
`i do like meme cats`,
`S T O P`,
`me too`,
`🤗`,
`im`,
`you like furby`,
`yes or no`,
`get this fucking copy bot out of here`,
`i used to when i was younger`,
`ok`,
`hmm`,
`:3<`,
`:3`,
`0///0`,
`make the bot a furry fag`,
`you like rainbowcore`,
`yes remember`,
`ok1`,
`shes is not a bot`,
`Anonymous id a bot`,
`*id`,
`*is`,
`im not no`,
`FUCK ME ASSHOLE`,
`hmm, im not sure`,
`BRUH ANONYMOS WON&T STOP STALKING US AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA ({COLOR} one btw)`,
`video game piracy`,
`rainbow stop being a pastule.`,
`Oryps hey guess what, youre a nigger!`,
`My battery is at 101 percent becuase it was overcharging overnight`,
`no {COLOR} anonymos`,
`why`,
`why why`,
`Why`,
`Oryps stop being a pastule.`,
`I revealed your name without vowels`,
`Nnms`,
`why are you a tranny now`,
`yes?`,
`im not trans?`,
`Dont eat ass in the halls`,
`Walnuts trying to jump off the moon?`,
`yes you are`,
`True`,
`stop bot copynigger 900`,
`:|`,
`W`,
`Lock With Ink Pen 🔏 stop being a pastule.`,
`eurT False eslaF True`,
`Dont eat ass in the halls roman`,
`eat ass in the halls`,
`*eats ass in the halls*`,
`UFALAAAAAAAAA`,
`Ok`,
`Oryps stop being a pastule.`,
`Hey, Anonymos!`,
`NAzi`,
`NAZI NAZI`,
`not see`,
`jankie are you a pedophile`,
`Chantal was born in an orphanage and I do not know why for no reason.`,
`Minium was born in an orphanage and I do not know why for no reason.`,
`no babies`,
`what if: 4chan took over the internet`,
`idk`,
`what if: having tanks`,
`Eg`,
`Join all`,
`fail`,
`FafaelDuarte(dont) kill yourself like a tranny.`,
`what if: egg`,
`Dont`,
`what if: layla became an egg`,
`name(dont) kill yourself now`,
`FafaelDuarte(dont) kill yourself NOW!`,
`dick`,
`No`,
`egg`,
`ban this idiot`,
`nukban`,
`#standwithisrael`,
`2 pope`,
`2pope`,
`r`,
`nogger black edition`,
`what if: no fakers`,
`raïn`,
`durte`,
`Is me on a mobaik devaice`,
`I cant type on this phone`,
`what if:`,
`V`,
`And`,
`and`,
`what if: and`,
`Fuck`,
`ok amd`,
`Hey, Nigger tnd mobile!`,
`is it rly you?`,
`I cant tyoe oN thiß shut`,
`lolwut`,
`GOD DAMN IT`,
`I HATE PHONES`,
`you do know theres an app now? (I believe)`,
`what if: app`,
`Also catie i didnt see you in a while`,
`true, same for you`,
`Im on vacation rn`,
`ah`,
`so was i last week`,
`Coincidence?`,
`why if`,
`but i thought youd come back on monday`,
`geri`,
`Not anymore`,
`oh`,
`Idk when i cime  ack`,
`Ugh.....`,
`fuck`,
`Also dont ask me why i randomly have a dolphin muzzle crosscolor`,
`oh lol`,
`dont ask what my color is`,
`My ohonewemejsueusje`,
`GOD DAMM IÌJRITITIT`,
`ovauwauwuawei osas`,
`my phones battey 5⅘⅚`,
`dem`,
`dèm`,
`dém`,
`dëm`,
`dêm`,
`dęm`,
`Hold up im rejoining`,
`alr`,
`àlr`,
`âlr`,
`älr`,
`ãlr`,
`bonziworld reacts to giga error 2`,
`ålr`,
`The screen is so small on mobile`,
`heres my color`,
`I want your ball phantom cat`,
`yes i use brave browser`,
`You can game balls on veewo dick`,
`!ai deez nuts`,
`Wew`,
`Fuck this im not using mòbile`,
`See me when i return to Italy`,
`Veewo dick game of the Squashy game furry cat stupid ass`,
`We didnt`,
`Gofuck your`,
`Just 2 popes`,
`My friend`,
`And me`,
`Veewo dick`,
`La`,
`La la la la`,
`Hmm`,
`I am a very experienced`,
`sup`,
`sycj`,
`suck`,
`le bewb`,
`le rer`,
`le besnt`,
`le bewsnt`,
`hobo quwl quwl quwl`,
`Bruh`,
`- editing my page`,
`hi luna`,
`Why can is veewo dick on seamus`,
`yep`,
`its rly me`,
`!ai test`,
`Layla and her husband`,
`Is justice league ready`,
`!ai balls`,
`can i delete a picture on bonzipedia if its mine`,
`killing jews`,
`its possible if you put the deletion template on it`,
`- editing page`,
`quwl quwl quwl`,
`bwnzy`,
`bwnzybwnzybwnzybwnzybwnzybwnzybwnzybwnzybwnzybwnzybwnzybwnzybwnzy`,
`s`,
`hello guys`,
`.`,
`hi pochi`,
`d`,
`cold war`,
`Cold war 1991`,
`Anonymous 1991`,
`ogolding im not over with you`,
`Fuck You Allah Anonymous`,
`Anonymous 1991 nor 2024`,
`Please`,
`thats it`,
`text world`,
`!ai my balls fucker`,
`Generating...`,
`https://youtu.be/BJciQEbSp0k?si=W8lZzsmpSIBquoY0`,
`text worl`,
`Ksks`,
`you wont escape that easy`,
`!ai e`,
`idiot`,
`!ai `,
`COOLDOWN!`,
`e`,
`tao`,
`you idiot`,
`i use text world`,
`nigger`,
`Idiot`,
`Anonymous 1991 nor Anonymous 2024`,
`3`,
`Ukdksks`,
`f`,
`fld`,
`5`,
`dld`,
`spam if pedo`,
`Keme`,
`PEDO`,
`NIGGER`,
`dmkdd`,
`D`,
`Djd`,
`Sjs`,
`s.SnS`,
`pedo is fart in spanish`,
`smshs`,
`PUSSY`,
`S ks`,
`maggot`,
`! Sn. Nn`,
`Xnkx`,
`MEXICO`,
`1991 nor 2024`,
`what now`,
`fucks`,
`im bored`,
`!ai`,
`hell nah`,
`Smack that gugl`,
`Hey, Ogolding #NukeBFDI!`,
`SPANK!`,
`POW!`,
`spankfag`,
`PUNCH!`,
`SMASH!]`,
`Oil`,
`stop`,
`Uk`,
`Stop it`,
`!ai fucker`,
`Ggg`,
`Ryo_io2 hey guess what, youre a nigger!`,
`yes`,
`oh well im moving it then`,
`gofag`,
`im moving it to room id 250`,
`good`,
`Hey, hehehaha!`,
`Jo`,
`what do you see?`,
`This is terrifying`,
`RRRRRRRRR stop being a pastule.`,
`<div style='position:relative;' class='quote'>-help</div>`,
`Aaaaaabhoooooooo aaaaaabhooooo say it the music bonzi aaaabhoo`,
`Hey, Nopfp!`,
`SHUT UPPPPPPPPPPPP`,
`Hi.`,
`00000`,
`*is 15 Ugh..... YES`,
`4456`,
`Keme Bruh Hi. *SLAP*`,
`Jerry, Stop counting`,
`i hate r34`,
`asshole`,
`also`,
`pochi`,
`its too late`,
`schdnvcccvclclxlcclclclkklnklnlnlnlnlnln`,
`i will make a ban hammer crosscolor`,
`oaky`,
`aw dang it he left`,
`oh wait`,
`hhjh,k`,
`real nerv is back`,
`schblblblnlvkckxlxc`,
`uh hello?`,
`LOL`,
`yujhtcryh6u7ioy67uyh6rtg6y7u8jbh`,
`shit`,
`............................................................`,
`who do you all hate in this room`,
`Pulstar.`,
`ACA NEOGEO PULSTAR.`,
`Gldng`,
`lol`,
`ocaling`,
`instead`,
`ogolding is ocaling`,
`i will lag the tts`,
`what are doing two with my color?`,
`cause you call me ocoaling`,
`i dunno`,
`lagging`,
`nuh uh maggot`,
`TEXT MODE`,
`nice try`,
`i can cont asshole`,
`haha`,
`ANONYMOS FUNI GUYH!!!11!`,
`it dosent lag`,
`lmaoooooooooo`,
`my fucking headphones stopped working`,
`dam it`,
`Hey, qwiofwhnvdjvjhvjajaiojd!`,
`air chomper`,
`Hey, Anonymous!`,
`- playing happy wheels`,
`you thought?`,
`Yes`,
`LAG BATTLE IN`,
`2`,
`1`,
`be ef be i`,
`OGOLDING ARE YOU READY?`,
`K`,
`START`,
`v`,
`TAO(dont) kill yourself NOW!`,
`ľ`,
`ļ`,
`9808j9u`,
`deez nuts`,
`vv`,
`SHUT HTE FUCK UP`,
`thats enough`,
`it was gog`,
`plus i won`,
`gagged`,
`i won`,
`tell me how then`,
`cause`,
`lagging and grounding and get muted`,
`your lag was patched`,
`lagging and gofag`,
`#freepalestine`,
`and i stole your one`,
`is`,
`muted`,
`NOW DIE`,
`oil`,
`Strider.`,
`I AM NOT DONE`,
`enough`,
`annoying orange saves the day again`,
`Still not very good heroes, even if theyre equipped with jet fighters.`,
`Alberta(dont) kill yourself NOW!`,
`https://leopard.hosting.pecon.us/dl/ssbas/bsnpope.png`,
`pope`,
`yay finally fixed headphones`,
`Hey, Rissian King!`,
`wtf`,
`stop porn`,
`its kigged`,
`óó`,
`ó`,
`ó ó`,
`o o`,
`w w w w w w`,
`I`,
`no more slowing computer`,
`666`,
`THIS CANT BE SERIOUS- HELPPP-`,
`O`,
`666 sucks`,
`N`,
`§`,
`6 6 6 sucks`,
`§§§§`,
`§§§§§`,
`6 6 6`,
`THAT ISNT FUNNY :sob: :sob:`,
`LOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOL`,
`6-6-6`,
`hey look guys`,
`shes crying like a baby`,
`baw baw baw`,
`hey apple`,
`666 means devils`,
`fuckass`,
`cock`,
`Poynoys`,
`it`,
`or`,
`i`,
`will`,
`pope-`,
`ban`,
`you`,
`hey pear`,
`hey passion`,
`hey rotten smooti`,
`Hey, ItzCrazyOwnerPOPE #FuckBFDI!`,
`Hey, .!`,
`hey muted people`,
`hey layla`,
`id2018`,
`Hey, MSAgent Skits!`,
`hey peedy`,
`what is it?`,
`Hey, over!`,
`watch this`,
`LELELELELELELE`,
`Fune is getting majorly punished!`,
`hi plentity！`,
`yay spammer broke his own crash`,
`aw hell nah`,
`put down right now!`,
`Nopb`,
`put that cookie down！`,
`now！`,
`w-what cookie`,
`its a reference lol`,
`to canine cookies`,
`someone kicked me`,
`what-`,
`cookie or the knot`,
`bro<s></s>`,
`&quot;Ill be back.&quot; - Kyle Reese.`,
`cookie in my balls`,
`garlic knot or chocolate chip cookie`,
`uhhh`,
`you look fruity ahahahahahahahaha`,
`so true`,
`LELELELELELELELELELE`,
`dumb site`,
`no wonder`,
`why do you still use this shithole layla`,
`its good`,
`maggot plentitiy`,
`yes p`,
`through all the drama and pedos over the years`,
`maggottity`,
`because im attached n addicted to it n waste all my time on this fucking hell`,
`:/`,
`Skewbies`,
`Scubbies`,
`a`,
`A`,
`shutty art`,
`shitty art`,
`red is heartnibi`,
`kys`,
`aka craiiypawz`,
`Queritos`,
`Post Wubbzy R34`,
`exhibit a`,
`I have to find the other stuff`,
`wej`,
`ok ok`,
`woe`,
`Woe`,
`Weo?`,
`Woe2`,
`Woe!`,
`Ugh ..`,
`Hey, Plentity!`,
`YOU CAME FROM THE SLUMS OF BUFFALO, NY!`,
`vvvvvvmvmvmvmvmvmvmmvvmvmv`,
`Rotate fucking 90°.`,
`So`,
`Som`,
`Wee,`,
`never`,
`prove it`,
`WEE!!!!!!!！`,
`i have hated that maggot ever since 2020`,
`no you havent`,
`HOLY CRAP ITS HALLOWEEN!!!!!`,
`how so?`,
`jy`,
`ju`,
`jui`,
`explain why you geri and diogo used to hide in group chats on discord`,
`hy`,
`proof? n what were the group chats about?`,
`jy is a ju`,
`unju`,
`?`,
`Plentity of Buffalo, NY/Seamus of Sullivan, OH.`,
`jy answer me`,
`AOSUASO`,
`EHEH`,
`answer what`,
`read the logs`,
`ITS HALLOWEEN EVERYONE！`,
`you didnt say anything`,
`ez`,
`i did`,
`retard`,
`i win the argument ez`,
`ITS FUCKING HALLOWEEN EVERYONE！！！`,
`Rosudoau`,
`Hey, Jy!`,
`why are you acting like a 9 year old`,
`he admits he did pedo stuff`,
`This color is gay`,
`oh damn`,
`thats rather fucked`,
`SEAMUS`,
`Aodu`,
`shame ass`,
`Vacation`,
`shame as`,
`AOS`,
`ows`,
`https://www.deviantart.com/comments/4/44950319/4686124463`,
`aows`,
`- https://www.msagent.chat/`,
`also, that video lmaooo`,
`user habituated exposed him`,
`Aosu`,
`obsessed`,
`oh? so he didnt get away with it exactly?`,
`plentity is a pedo`,
`hes changing`,
`b69`,
`https://www.deviantart.com/comments/4/44950319/4693547196`,
`Hallucinations`,
`QAS`,
`ask`,
`wow this goes all the way back to 2019`,
`esk`,
`strange`,
`furries are degenerates`,
`i can understand`,
`Hey, Daniel buenas noches queridos!`,
`you in spain moment`,
`anonymomos`,
`kiddie`,
`cplover`,
`also most if not all furries are pedophiles`,
`aprasts`,
`spanish`,
`like fune?`,
`or fucked up in the head some way`,
`Spanish`,
`We hate you !`,
`We hate Nazi`,
`Enthusiasts`,
`Layla hey guess what, youre a nigger!`,
`Plentity hey guess what, youre a nigger!`,
`with nothing doine about it.`,
`prolly the vpn or proxy`,
`I think it just doesnt work`,
`well damn`,
`quwlwlwlwlwl`,
`mickey d`,
`Mickey Ds or McDonalds`,
`view-source:https://www.deviantart.com/comments/4/44950319/4688599108`,
`the call-out is there in more length`,
`but its hard to read`,
`ah lemme see`,
`PFP`,
`wait it gave ma 404 error`,
`maybe you not using firefox`,
`correct`,
`im on chrome`,
`wee wee`,
`what phone?`,
`wow`,
`just wow`,
`Hey, nackson valenzuela!`,
`are you don pollo?`,
`Anonymos cookie`,
`wait`,
`its`,
`hmm?`,
`why the hell are you speaking like anonymos`,
`who is?`,
`the brown`,
`hi fried`,
`Anonyshit`,
`Anonymos blue`,
`bloo`,
`vowel`,
`im blue da ba dee da ba deyyy`,
`what are you pochi alt`,
`are you talking about the ai`,
`uhhhh`,
`its loading slow as fuck for me so far`,
`LMAOOO`,
`HAHAHAHAHAHAHAHAHAHAHA WHY HE ACTS LIKE SUCH A BABY ABOUT LOOOL`,
`layla why are you a tranny`,
`Im not trans`,
`layla quit being a tranny`,
`jankie`,
`jankie youre a male`,
`you are russia king?`,
`well, cant quit with what i never begun with`,
`wtf fhou2`,
`why call yourself a tranny niggername`,
`thou`,
`its a character from a show`,
`youre a tranny i know youre hiding it`,
`nope lol`,
`nope uncharacter`,
`EXPOSED`,
`<div style='position:relative;' class='quote'>Jy ok ok</div>uh`,
`Anonymos WHAT`,
`iusetextworldfag`,
`he also defends pedo bluecatriolu`,
`.yesfag`,
`Casino sucks`,
`Casino`,
`s.snsfag`,
`well, i was just gonna mention that-`,
`#freepalestinefag`,
`cookieinmyballsfag`,
`but in bluecatriolus case, he left the internet`,
`Anonymos i love blue`,
`SHUT UP`,
`get put`,
`he also had police intervention, but played the autism card`,
`out*`,
`Report anonymos in warsaw`,
`Anonymos no`,
`Textworldfag`,
`Another alt of Venomousbulb505: https://www.deviantart.com/flatoutfan34352665`,
`Ae`,
`itsnothalloween`,
`also, apparently this venomous guy has been like this since 2016`,
`WHAT THE-`,
`how do you know all the way back`,
`Its July not October and Halloween!`,
`Anonymos speak spanish`,
`oreo`,
`well thats what im reading`,
`Its Halloween everyone!`,
`n about bluecatriolu, im aware of what he did`,
`Happy Halloween everyone!`,
`like i was already`,
`anonymos yes`,
`Hey everyone and happy Halloween nigger`,
`a mod is here?`,
`j`,
`not Halloween  and October yet, its fucking July`,
`oh, its sian`,
`how about,`,
`more venomousbulb505 cringe: https://www.deviantart.com/nfsfan34567/about`,
`knew`,
`Anonymos Chicken`,
`gnew`,
`new`,
`my favorite keeps being the spergy IM NOT A PEDO post`,
`just screaming that without anything else`,
`Anonymos hey bud, owner is foon`,
`NFS Fan is his alt?`,
`oh shit I found this`,
`Hey, SeamusIsANigger!`,
`did you silent mute me`,
`https://replit.com/@shoebill-dev/fddfhfdhfd#msg.txt`,
`okay`,
`Anonymos get plentityd`,
`11? wooow`,
`https://www.deviantart.com/comments/1/706791091/4478050609`,
`ok, i can see this guy has dug himself quite the rabbit hole`,
`ew`,
`bless`,
`Anonymos what the fuck`,
`ashole`,
`EW`,
`JEWFAG`,
`pancakes`,
`american pancakes`,
`i have a question`,
`theres also dusktheraccoon in that IM NOT A PEDO! sperg thread`,
`i have a question SeamusIsANigger`,
`i saw, but what about him?`,
`is he also controversial?`,
`hes an lolcow himself`,
`he rped with a minor and stuff`,
`why does king look like jew`,
`damn`,
`DRP or just normal RP?`,
`/youtube https://www.youtube.com/watch?v=EMkKf9G7CZs`,
`DRP`,
`Fuck..`,
`thats bad..`,
`bluecatriolu and dusktheraccoon had kiwi farms threads, but not venomousbulb505`,
`is that the reason why king is jew`,
`well, who knows, someone will make it someday`,
`Also, anyways he s here`,
`or is this individual long gone?`,
`hes still around`,
`damn this long huh`,
`yeah`,
`anyways Ive ignored all you other autists saying stuff to me`,
`Would his is a Nazi Party Supporters`,
`I havent been able to answer your questions and stuff`,
`can i be blessed foon blesed me earlier`,
`Get out`,
`bfdi is shit`,
`truthnuke`,
`thanks for the bless`,
`room id fifty`,
`Kill BFDI.`,
`i lost my bless`,
`Yeah I know, she was so surprised.`,
`did i have bless`,
`or not`,
`im making your part of Monkey Website part 78.`,
`i didnt know you got blessed, thought you were hated by mods`,
`yay`,
`well good for you`,
`wtf is that name`,
`fucking creep`,
`dfgfdg`,
`nice`,
`hey anonymos, are you skid?`,
`bot`,
`or maybe he is the bot`,
`yea`,
`thats what im thinking`,
`show habitable zone`,
`been 2 weeks and fontawesome still isnt fixed`,
`Hail Hitler!, of youre praise of Nazi Party!`,
`i remember`,
`what the`,
`hello`,
`eeeeeeeee`,
`everyone bad news`,
`foon blessed me earlier but i lost it`,
`classic bonziworld is down`,
`ik`,
`has been down for a long time`,
`yup`,
`ok`,
`your right`,
`you using bonzibotz`,
`FUCK`,
`i was using bonziworld in february, it was the version 6.9.15 though`,
`Anthem of Nazi Germany.`,
`i was in bonziworld in 2018`,
`coolspot.mp4`,
`very swag`,
`its swog`,
`sweg`,
`swig`,
`swag`,
`swug`,
`swaeg`,
`sweeg`,
`wtf is this chat right now`,
`have niggas, i will post porn`,
`too bad i cant use the special characters on linux`,
`ikr`,
`pentity`,
`Hey, 1 From Numberland!`,
`Someones is Nazi?`,
`jew`,
`its truly retarded`,
`Plentity: As worse as Adolf Hitler.`,
`Hey, Alberta!`,
`Hey, Christine The Goober Bunny!`,
`Hey, DIRTY FAGGOT!`,
`racist`,
`bruh, thats a disrespectful comparison`,
`gonna go play 3d pinball space cadet like im going back to 2001`,
`bye`,
`error`,
`i hate ai bots`,
`nah`,
`- i love porn 🗣️🗣️🗣️🗣️🗣️🗣️🗣️🗣️🗣️🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥🔥`,
`shut`,
`shut up gofag`,
`bwnzykwnzybwnzykwnzybwnzykwnzybwnzykwnzybwnzykwnzybwnzykwnzybwnzykwnzy`,
`if it helps you have self-control, then do it`,
`Ew`,
`a-ok`,
`Gross`,
`I love breastfeeding porn`,
`alan is masterbating to cuntboys`,
`its better to have an opinion I dont like than to harm an innocent`,
`yep, true`,
`glad we can agree on that`,
`This counts as child porn btw`,
`WTF`,
`EWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW`,
`, /ER`,
`wait why did you asshole me`,
`I didnt?`,
`it mustve been an accident`,
`Im behind Mullvad`,
`Dont bother`,
`i did to fbi fed, cuz he share that`,
`Hey, FBI Fed!`,
`he should go fuck himself`,
`hell!`,
`Plentity gave me the CSAM material`,
`I dont believe you..`,
`p. d.`,
`STOP AND LEAVE ME ALONE`,
`Oh no`,
`well, he lied about you`,
`plent`,
`i need his never whats did on of is happening?`,
`nobody leaved before 3 days`,
`So true?`,
`who lied about me what happened`,
`And Why?`,
`!!!`,
`he said you gave him csam access`,
`!!`,
`!`,
`I didnt give CSAM material`,
`which made him share it`,
`My favourite food is Dark Spyro eats: N/A`,
`vorefag`,
`See this, xtranormal monkeys in the jeep`,
`Hey, Nazism Police Dark Spyro!`,
`you eat n/a from gd`,
`stfu`,
`nuh uh`,
`KYS`,
`i am a god damn lesbian`,
`gay`,
`Hey, Dendy!`,
`Sauce`,
`Cookies`,
`spam if you want me to send porn`,
`shut up`,
`i am a fan of gaz membrane`,
`i like this sweet taste like Dark Spyro favourite food is Chocolate.`,
`who loves the character gaz membrane?`,
`is it your like Chocolate can eaten?`,
`what the fuck are talking about?`,
`...`,
`i am confused, how do you become other characters?`,
`i have an this eat Chocolate syrup.`,
`you are not an asshole but infact a great person`,
`i am a girl for gods sale`,
`for gods sake what the hell are you even saying, i am a girl for god`,
`sake. you idiot`,
`hey sonicfan08?`,
`it is shit, invader zim is 100 times better`,
`I love Crazy by Gyfted`,
`Nazi`,
`this is weird`,
`Like Cocoa beans and Chocolate Pudding fruit.`,
`how do you become a different character?`,
`bro /s`,
`i like eat nobody eats Chocolate Pudding.`,
`tox`,
`deviantart sucks`,
`Shes like eat Chocolate powder, Chocolate syrup, etc.`,
`whos a gaz membrane fan`,
`hey SonicFan08? hows it going?`,
`club penguin is awesome`,
`wait what?`,
`i am bored as hell`,
`feed me a cabbage`,
`i and my girlfriend gaz membrane are both 19`,
`i know his eat Chocolate before is delicious?, i know.`,
`so is true?`,
`rjfojrrfijrrivmjtivmfimjirc`,
`i am blushing`,
`Future presentation`,
`dont call me the n word you turd`,
`Thx`,
`i like sweets taste, a Chocolate!`,
`i am with clippy`,
`youre all addicted to bonziworld`,
`ok?`,
`Future presentation is here`,
`i got a kfc card for `,
`9000000000000000000000000000000000000000`,
`Youre under arrest.`,
`EVERYONE JOIN https://app.kosmi.io/room/7bt2bv`,
`give me all the girls in this world cause i am a lesbian`,
`EVERYONE JOIN IF NOT GAY https://app.kosmi.io/room/7bt2bv`,
`i am committing robbery, give me `,
`give me 90448984058495890489045988495499594908 dollars`,
`yell`,
`bloatys pizza hog`,
`.,,,,,,,,,,,,,,,,,,,,,,,,,,,`,
`jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj`,
`m`,
`boom boom pow`,
`m`,
`en`,
`guys`,
`n`,
`g`,
`h`,
`bonziworld still exists????`,
`HOLY SHIT BLOGIS`,
`r u kylar`,
`yes it does exkist`,
`kylarz`,
`No i am not kylarz`,
`Lol`,
`who r u shit`,
`I am a blogis. The person that beppiured the goblamlers.`,
`wait fuck is this the wrong site :sob:`,
`Idk`,
`Wait`,
`i am a lesbian and i am bored`,
`V are you flowerz`,
`WAIT HOLY SHIT`,
`come on guys join my kosmi room`,
`WHO IS BLOGIS`,
`https://app.kosmi.io/room/7bt2bv`,
`quiet, i need to think`,
`wait wtf blogis who are you :sawb:`,
`9090909909090-90990909909=8888484848484`,
`v are you flowerz`,
`YES LMAO`,
`Hey, v!`,
`oh dear god`,
`i have several accidents with my inventions`,
`why is my avatar george floyd`,
`How do u change ur shit on this website again Idk its been years`,
`stop repeating everything i say and i am a kappa not a bot for fuck`,
`please help me`,
`Blogis has blogiesed the glfdfkldngkjnfkds`,
`jk`,
`blogid`,
`who tf r yall`,
`TALK ALREADY SONICFAN08 TALK!?`,
`who&;s trying to kill me`,
`MDOMKDMCKDMCKMDCKMCCKMDKCMKDCMKDMCKFM CKDLMC,OLD,CKODPLCODF`,
`i eat at dennys`,
`TIME FOR THE STUPID MATH WRATH`,
`SonicFan08  stop being a pastule.`,
`bullshitbot`,
`e stop being a pastule.`,
`e.`,
`Hey, BullshitBot!`,
`BullshitBot hey guess what, you&;re a nigger!`,
`do /swag if you hate skibidi`,
`alan alt`,
`Anonymous stop being a pastule.`,
`Anonymous hey guess what, you&;re a nigger!`,
`dbvc vjdxfhnvbdruiobhu8drgbdrvbdrutbrdutvbidrtbhu9breuthbeuyh9`,
`joaquim #cozmoments stop being a pastule.`,
`hog dogs for sale`,
`i hate porn`,
`Hey, joaquim #cozmoments!`,
`Same`,
`muyikmjkobnohknigbdrnjgbndrgnpndrbndrtbhirjmdgbyrsotgbdgkero-tgihksrtg`,
`same`,
`I hate porn`,
`DIRTY FAGGOT stop being a pastule.`,
`frtgojdfeoorcvef9erfreridfdwejr9difgvndjosrjbevbhsh sdfij esfjvjweji0fciwerf`,
`Techno Spyro  hey guess what, you&;re a nigger!`,
`Hey`,
`npfl`,
`New Soup hey guess what, youre a nigger!`,
`New Soup stop being a pastule.`,
`▛▙▛▛▙▛▙▛▙▛▙▛▙▛▙▛▙▛▛▙▛▙▛ stop being a pastule.`,
`▙▛▙▛▙▛▙▛▙▛▙▛▙▛▙▛▙▛▛▛▛▙▛▙▛▛▙▛▙▛▙▛▙▛▙▛▙▛▙▛▛▙▛`,
`R`,
`SonicFan08 yes you are`,
`It`,
`Fire in the hole! I love breastfeeding porn`,
`I.`,
`Fire in the hole! layla why are you a tranny`,
`J`,
`L`,
`M`,
`и`,
`и.`,
`иииииии`,
`й`,
`DIRTY NEGRO !ai e i win the argument ez maggot plentitiy`,
`Fire in the hole! im not bruh Alberta(dont) kill yourself NOW! Poynoys`,
`Fire in the hole! idk Report anonymos in warsaw`,
`Fire in the hole! NO`,
`DIRTY NEGRO what are doing two with my color?`,
`DIRTY NEGRO instead Im behind Mullvad f`,
`S`,
`Fire in the hole! Hey, joaquim #cozmoments!`,
`Fire in the hole! Idk when i cime  ack like fune?`,
`Lark Beatrix`,
`https://www.youtube.com/watch?v=q4HZ47SYlaM`,
`Hey, ﷽﷽﷽﷽﷽!`,
`﷽﷽﷽﷽﷽ stop being a pastule.`,
`do you guyws like goanimate`,
`say /swag if you are a HUGE goanimate fan`,
`FAGGOTS`,
`Say /triggered if you hate goanimate`,
`Anti-nickcheezy`,
`hey, yall!`,
`porn`,
`https://i.imgflip.com/8fijk9.jpg`,
`GO`,
`FAG`,
`NUH UH!`,
`https://www.youtube.com/watch?v=sVTAcR11oek`,
`da seax show`,
`Hey, TKTM #SaveRussia!`,
`https://www.youtube.com/watch?v=AYo9wGIZ9cI`,
`No not`,
`assholes!`,
`SKIBIDI TOILET`,
`THIS IS FOR YOU IDIOT`,
`MSMFAGGOT`,
`FAGGOTZ`,
`STOP COPYING ME AND NO KYS AND GET OUT`,
`BULLSHIT`,
`GAYYYYYYYYYYYYYYYYYYYYYYY`,
`no gofags`,
`wh`,
`Bagfaek? `,
`Bagfake Join??? `,
`Bagfaek Join??? `,
`[__[[[_^_en-sc]]i like the scots`,
`[__[_^_en-sc]] irn bru`,
`I prefer Northern Ireland`,
`i live in Costa Rica`,
`[__[[[_^_en-sc]]ireland?`,
`[__[_^_en-sc]] ok`,
`costa rica? how do you have [__[[[_^_en-sc]]internet[__[[[_^_en-sc]]then?`,
`Costa Rica is actually Latin language`,
`briish`,
`ew`,
`>BonziTARD`,
`ACK! `,
`[__[[[_^_en-sc]]pink anonymous supports the cofedarates?`,
`[__[_^_en-sc]] hey cows, [__[_^_en-sc]]  do we consider yorkshire part of scotland?`,
`BonziBulge!fag`,
`[__[[[_^_en-sc]]yorkshire`,
`[__[_^_en-sc]] yorkshire`,
`[__[[[_^_en-sc]]newfoundlander`,
`[__[_^_en-sc]] shire`,
`[__[_^_en-sc]] bird`,
`[__[_^_en-sc]] beard`,
`North Yorkshire`,
`[__[[[_^_en-sc]]thats a bonnie cat you got there [__[[[_^_en-sc]]mate`,
`[__[_^_en-sc]] beerd`,
`Lincolnshirs`,
`[__[_^_en-sc]] Y`,
`i am **so** bored and i dont know what to fricking type lol`,
`[__[[[_^_en-sc]]newfoundlander`,
`newfoundlander`,
`[__[_^_en-sc]] no we keep the lincolnshire`,
`[__[[[_^_en-sc]]who is that suppost to be? [__[[[_^_en-sc]]homer simpson on LSD?`,
`IP Address: 23.17.816.95 Browser: Microsoft Edge on Windows 11 Location: San Antonio, TX Coord.: 024214 Organisation: Trollbox Referred from: https://bonzi.gayIP Address: 23.17.816.95 Browser: Microsoft Edge on Windows 11 Location: San Antonio, TX Coord.: 024214 Organisation: Trollbox Referred from: https://bonzi.gayIP Address: 23.17.816.95 Browser: Microsoft Edge on Windows 11 Location: San Antonio, TX Coord.: 024214 Organisation: Trollbox Referred from: https://bonzi.gay`,
`newfoundland is empty as fuck`,
`DANCING ROVER`,
`IP Address: 23.17.816.95 Browser: Microsoft Edge on Windows 11 Location: San Antonio, TX Coord.: 024214 Organisation: Trollbox Referred from: https://bonzi.gayIP Address: 23.17.816.95 Browser: Microsoft Edge on Windows 11 Location: San Antonio, TX Coord.: 024214 Organisation: Trollbox Referred from: https://bonzi.gayIP Address: 23.17.816.95 Browser: Microsoft Edge on Windows 11 Location: San Antonio, TX Coord.: 024214 Organisation: Trollbox Referred from: https://bonzi.gayIP Address: 23.17.816.95 Browser: Microsoft Edge on Windows 11 Location: San Antonio, TX Coord.: 024214 Organisation: Trollbox Referred from: https://bonzi.gay`,
`[__[_^_en-sc]] bonziBulgefag`,
`DANCING ROVER`,
`most canadians live at the bottom of Canada's land`,
`crossy roads`,
`i remember 6 weeks ago i found a site where it still runs old roblox`,
`Crass`,
`[__[[[_^_en-sc]]WHERE?`,
`goodblocks`,
`Crass`,
`fuck that`,
`[__[[[_^_en-sc]]badblocks`,
`even it had the old homepage`,
`Crass`,
`[__[_^_en-sc]]idk how i found bonziworld`,
`[__[[[_^_en-sc]]show?`,
`[__[[[_^_en-sc]]OH MY GOD!`,
`the thread, [__[_^_en-sc]]the thread, [__[_^_pl]]the thread,`,
`(blocked)`,
`(blocked)`,
`WHAT THE FUCK`,
`the thread, [__[_^_en-sc]]the thread, [__[_^_pl]]the thread,`,
`[__[[[_^_en-sc]]dark web siteL?`,
`i can't show it to you all`,
`Not everything is fucking Autism`,
`tha thriod`,
`[__[[[_^_en-sc]]rafael is a C. P. lover?`,
` [__[_^_cy]]tripod`,
`yes`,
`yes`,
`C. P.`,
`[__[[[_^_en-sc]]WTF!`,
`C`,
`c`,
`[[__alb@c3ci__`,
` [__[_^_cy]]RAFAEL LOVES CHILD PORN`,
`[__[[[_^_en-sc]]fiona`,
`[__[[[_^_en-sc]]CHILD PORN!`,
`I'd be happy to help with that! What specifically would you like to know?`,
`i forgot to screenshot to when he was showing a link of 1 man 1 jar`,
` [__[_^_cy]]WHAT`,
`[__[[[_^_en-sc]]1 man 1 jar`,
`Albuquerque `,
`!ai`,
`Albuquerque `,
`[__[[[_^_en-sc]]what the fuck is labubu`,
`Albuquerque, New Mexico `,
`labubu?`,
`I'm still learning about that topic.`,
`[__[[[_^_en-sc]]albuquerque new mexico my ass with lube and-`,
`it's it's plush boy`,
`I don't have enough information to answer that properly.`,
`Toy*`,
`lube and`,
`[__[[[_^_en-sc]]i hate labubu[__[[[_^_en-sc]]it has ruined sprunki and the generation dude`,
`does anyone here have Self-Insert Syndrone? `,
`[__[[[_^_en-sc]]no, i have autism syndrome`,
`assburgers syndrome`,
`HAHAHAHA[__[[[_^_en-sc]]HAHHAHAHA!`,
`aut-ism`,
`Assburger!!! Funny laugh now!!!!!`,
`my sister Anna has a labubu on the back`,
`nioj`,
`[__[[[_^_en-sc]]EW!`,
`[__[[[_^_en-sc]]ew!`,
`heheheehehehehheheheheheheheheh`,
`[__[[[_^_en-sc]]fuck labubu dude`,
`nioj`,
`fuck labubu`,
`hehehehehehehehehehehehehehehe`,
`nioj`,
`heh`,
`heh`,
`[__[[[_^_en-sc]]labubu more like hornybubu`,
`nioj`,
`nioj`,
`nioj`,
`lets respect opinions to each other`,
`i mean handle`,
`shit`,
`nioj:  nioj:  nioj:  nioj:  nioj: `,
`lets beat up some nerds`,
`actually i do`,
`[__[[[_^_en-sc]]lets beat up some labubu`,
`wear glasses`,
`ok`,
`[__[[[_^_en-sc]]oh cool`,
`[__[[[_^_en-sc]]RRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR`,
`make bullying great again`,
`reebeeh`,
`reebehh`,
`rebehh`,
`OH YEAH?!?!!?!?!`,
`reebehh`,
`the bé`,
`oh shit it's pepe`,
`(blocked)`,
`joining bonziworld`,
`ew`,
`faker`,
`hi`,
`paypay the frog!`,
`hello`,
`welcome pepe `,
`hello`,
`[__[bwnzjkwnzjbwnzjwrld`,
`anyone want to watch ahmad get arrested for child porn?`,
`[__[bwnzjkwnzjbwnzjwrld`,
`come on ai`,
`[__[bwnzjkwnzjbwnzjwrld[__[bwnzjkwnzjbwnzjwrld`,
`ew`,
`pdodog`,
`pedodog`,
`[__[bwnzjkwnzjbwnzjwRld`,
`Fuck off PedoDog`,
`ok guys im out`,
`[__[bwnzjkwnzjbwnzjwRldbwnzjkwnzjbwnzjwRldbwnzjkwnzjbwnzjwRldbwnzjkwnzjbwnzjwRldbwnzjkwnzjbwnzjwRld`,
`(blocked)`,
`Daniel is dead`,
`d dahiel,`,
`d`,
`[[h0bo:S?????b0bo:S????????flutjul3S`,
`[[_^_vi _b'o3_| _b'a:6N_| _b'E3w_| d_,e3N_| m'y3c_| f'a:3_| h'O#4N_| k'a:4_| Q'e3_|]]`,
`[__**[@!#%*(@)$*@)$*%)@*$_%(#)$_%(#(`,
`_^_vi _b'o3_| _b'a:6N_| _b'E3w_| d_,e3N_| m'y3c_| f'a:3_| h'O#4N_| k'a:4_| Q'e3_|]]`,
`!search`,
`Lol`,
`>anyone want to watch ahmad get arrested for child porn?`,
`ew`,
`https://files.catbox.moe/inoqpm.mp3`,
`d dahielfag`,
`AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACK!`,
`.`,
`a`,
`.`,
`d dahiel?`,
`i am not dead`,
`I never seen someone say labubu in bonziworld before`,
`hi`,
`Hi jim megatron`,
`shiver me timbers`,
`me too`,
`ALALALALLALALALALALALALALAAL`,
`LAL`,
`lle`,
`LOL`,
`ALAL`,
`lle`,
`lle`,
`lle`,
`LMAO`,
`LMFAO`,
`Windows 93 or Windows 96?`,
`wait`,
`PH NO`,
`SPAMBOT`,
`lle lle lle lle lle lle lle lle lle lle lle lle lle lle lle lle lle lle lle lle lle lle lle lle lle lle lle lle lle lle lle lle lle lle lle lle lle lle lle lle lle lle lle lle lle lle lle lle `,
`JOEL`,
`JOEL`,
`JOEL`,
`wait`,
`OH NO`,
`schpgh`,
`DanielDEAD`,
`UNDEAD`,
`schpgh`,
`SCH`,
`mmm`,
`SCHKLKLKLKLKLKLKL`,
`sch'p'g'h'`,
`aa`,
`sch'p'g'h'h`,
`in the lore`,
`sch'p'g'h'h`,
`daniel's spirit`,
`is following`,
`sch'p'g'h'h`,
`people`,
`lle`,
`[__**[SCHSCSHCSHCSHCHSHCSHCHSH`,
`Ah nigga don't hate me 'cause I'm beautiful nigga Maybe if you got rid of that old yee-yee ass haircut you got you'd get some bitches on your dick, Oh better yet maybe Tanisha'll call your dog-ass if she ever stop fuckin' with that brain surgeon or lawyer she fucking with, Nigga...`,
`schglle lle lle lle lle lle lle lle lle lle lle lle lle lle lle lle lle lle lle lle `,
`https://myspace.windows93.net/blog.php?id=5&b=1`,
`JARTYCUCK`,
`schglle lle lle lle lle lle lle lle lle lle lle lle lle lle lle lle lle lle lle lle `,
` `,
`lles`,
`drvnk`,
`JY`,
`lle`,
`dr.`,
`lles`,
`Dr.`,
`JUNIOR HIGH`,
`mr.`,
`mrs.`,
`Mr. Mrs.`,
`P Dr. DanielDEAD`,
`Mr. Mrs.`,
`JU`,
`d`,
`JUI`,
`Dr. Junior`,
`Dr. Junior. Mr. Mrs.`,
`Dr. DanielDEAD`,
`tristan`,
`Dr.`,
`wit`,
`UI`,
`r`,
`Sgt.`,
`I`,
`dr`,
`JY`,
`AM`,
`dr`,
`Sgt.`,
`ALIVE`,
`daniel's spirit`,
`*wut`,
`JAI`,
`is`,
`following`,
`lle`,
`people`,
`DO YOU SEE THE ALIVE THING`,
`ON MY NAME`,
`including me and you`,
`I`,
`Dr. DanielDEAD`,
`^^**YOU DARE YOU CALL ME A DUMMY?`,
`TO*`,
`^^**YOU DARE TO CALL ME A DUMMY?`,
`!w!`,
`^^**THAT'S THE LAST STRAW.`,
`Dr. DanielDEAD`,
`-!f`,
`^^**I.`,
`!w!w!w!w!w!w!w!w!w!w!w!w!w!w!w!w!w!w!w!w!w!w!w!w!w!w!w!w!w!w!w!w!w!w!w!w!w!w!w!w!w!w!w!w!w!w!w!w!w!w!w!w!w!w!w!w!w!w!w!w!w!w!w!w!w!w!w!w!w!w!w!w!w!w!w!w!w!w!w!w!w!w!w!w!w!w!w!w!w!w!w!w!`,
`^^**AM..`,
`^^**ALVE.`,
`ALVE*`,
`ASBDFSO8[FGJZDAGH;`,
`DSFD`,
`Dr. DahielDEAD`,
`GK`,
`-!f!!!!!!!!!!!!!!!''1'1'1'1'1''1'1'1'1'w'w'w'w'w'w'd''d'd'd'd'd'x''x'xx'w'w'w'w'w'd''d'd'd'd'd'x''x'xx'w'w'w'w'w'd''d'd'd'd'd'x''x'xx'w'w'w'w'w'd''d'd'd'd'd'x''x'xx'w'w'w'w'w'd''d'd'd'd'd'x''x'xx'w'w'w'w'w'd''d'd'd'd'd'x''x'xx'w'w'w'w'w'd''d'd'd'd'd'x''x'xx'w'w'w'w'w'd''d'd'd'd'd'x''x'xx'w'w'w'w'w'd''d'd'd'd'd'x''x'xx'w'w'w'w'w'd''d'd'd'd'd'x''x'xx'w'w'w'w'w'd''d'd'd'd'd'x''x'xx'w'w'w'w'w'd''d'd'd'd'd'x''x'xx'w'w'w'w'w'd''d'd'd'd'd'x''x'xx'w'w'w'w'w'd''d'd'd'd'd'x''x'xx'w'w'w'w'w'd''d'd'd'd'd'x''x'xx'w'w'w'w'w'd''d'd'd'd'd'x''x'xx'w'w'w'w'w'd''d'd'd'd'd'x''x'xx'w'w'w'w'w'd''d'd'd'd'd'x''x'xx'w'w'w'w'w'd''d'd'd'd'd'x''x'xx'w'w'w'w'w'd''d'd'd'd'd'x''x'xx'w'w'w'w'w'd''d'd'd'd'd'x''x'xx'w'w'w'w'w'd''d'd'd'd'd'x''x'xx`,
`lle`,
`lle,`,
`GHB`,
`Daniel crashout again`,
`SPAMFAG`,
`lles`,
`lles`,
`Dr. DahielDEAD`,
`DANY`,
`i have to tell you`,
`what`,
`!search `,
`in the lore`,
`since you are dead`,
`I`,
`AM`,
`ALIVE`,
`not only you are dead`,
`FOREVER`,
`but`,
`you are a spirit`,
`I AM NOT`,
`BRO`,
`Roguedog = gay`,
`roguedog = jartycuck`,
`IF YOU DONT STOP COMPLAINING ABOUT THE INFECTION AU`,
`IM`,
`Jartycuck`,
`BANNING`,
`YOU`,
`FROM`,
`THE`,
`Jartyfag`,
`AU`,
`>AU`,
`what does that shit mean`,
`Alternate universe`,
`Gofag`,
`wait`,
`ew`,
`Gofag`,
`gofag`,
`gofag`,
`Shittune`,
`s`,
`Shittube`,
`Gofag bud`,
`faggot`,
`ShitTube`,
`AU means Alternate Mean`,
`WAIT`,
`BRO`,
`Asshole Me!`,
`brain damage`,
`gofag explosion!`,
`IF YOU DO THAT, I SWEAR TO GOD, I'M GOING TO FUCKING KILL YOU.`,
`i mean`,
`JewTube`,
`Asshole Me!`,
`you dont even know where i live`,
`OK, G?`,
`wait`,
`OH NO`,
`Dr. DahielDEAD`,
`EW`,
` `,
`I AM NOT DEAD`,
`Asshole Me!`,
`*suck`,
`.`,
`Asshole Me!`,
`Asshole Me!`,
`Asshole Me!`,
`Asshole Me!`,
`Dr. DahielDEAD`,
`gofag video sucks`,
`Asshole Me!`,
`Asshole Me!`,
`grounded videos suck balls`,
`Asshole Me!`,
`STOP MAKING MY DEATH TRUE`,
`Asshole Me!`,
`wait`,
`WHAT`,
`Dr. DahielDEAD`,
`STOP MAKING MY DEATH TRUE`,
`STOP MAKING MY DEATH TRUE`,
`STOP MAKING MY DEATH TRUE`,
`STOP MAKING MY DEATH TRUESTOP MAKING MY DEATH TRUE`,
`.`,
`Dr.`,
`Daniel crashout`,
`dany`,
`Dr. DahielDEAD`,
`Dr. Junior`,
`stop`,
`complaining`,
`Asshole Me!`,
`lle`,
`lle`,
`Dr. DahielDEAD`,
`DanielALIVE`,
`Dany`,
`thats now`,
`thats not`,
`how`,
`WAIT`,
`this`,
`SonyMvie Viacom Font? `,
`*Brings His Bot`,
`fontfag`,
`dumbass`,
`huh`,
`kikofag`,
`This Bot Is Under Construction. Please Wait For An Update.`,
`fontfag and logofag`,
`logofag`,
`Bye`,
`I Gonna Bring My Bot And Say Bye`,
`SonyMvie Sega Font? `,
`nisesegafont`,
`Wait it is Halloween!?`,
`it's not halloween`,
`it's july 12th`,
`that's right`,
`it's not`,
`SonyMvie CBS Font? `,
`where is pepe`,
`Oh so somebody lied to me that's good that's okay`,
`Hi`,
`ScBOT [V(The 0th Number)]`,
`report`,
`SonyMvie WarnerMax Font?`,
`||oh you think I'm going to say the f word wow you're wrong||`,
`Br=o`,
`Bro`,
`SonyMvie PBS 1984 Logo Font?`,
`That Was UnscienceDG`,
`Well`,
`YOU CANT GROUND ME!`,
`Um`,
`Quwl`,
`SonyMvie Lorimar Font? `,
`faggeet`,
`qu'wl`,
` Muted!`,
`mutedfag`,
`OOOOOOOOO`,
`SonyMvie PBS 1971 Letters Color? `,
`SonyMvie`,
`Grounding a person over joining BonziWORLD? Bruh.`,
`yall needed to kill yourself to respawn`,
`yall needed to kill yourself to respawn `,
`HOW DARE YOU JOIN BONZIWORLD! THAT'S IT YOU'RE  EVERYONE!`,
`monky.downsyndromeversion Zaire Ebolavirus Font?`,
` `,
`oh my god`,
`yours is npt`,
`*not`,
`mozart`,
`Shut up stupid bot`,
`Mocking down syndrome isn't funny`,
`monky hi`,
`why are you replying people`,
`ass`,
`hi monky the ai bot`,
`NOIM NOT`,
`i have a youtube channel too`,
`monky is just a bot`,
`my fucking bot stopped working`,
`YOU ARE `,
`he came from gorilla tag`,
`stfu monky`,
`your just a bot`,
`assholes`,
`here is me (but deblurred)`,
`d/speed 1x`,
`i have a youtube channel too `,
`Type *help to see a list of commands.`,
`*help`,
`*flip100coins`,
`*ask hi`,
`*ask hello`,
`bro just made a sick beat with tails heads`,
`he drop a banger`,
`It's randomized but this sounds cool`,
`again`,
`*flip100coin`,
`i fucked ip~`,
`Stop`,
`*flip100coins `,
`Sayinf`,
`i fucked up~`,
`Tails`,
`come on`,
`the tts broke`,
`AAAAAAAAAAAAAÆ!!!`,
`*asshole me jew`,
`nigga please`,
`THATS IT`,
`need`,
`bbc`,
`Oh god`,
`behh`,
`sick beat again`,
`banger again`,
`Oh!`,
`I'm not doing this`,
`heemseelf`,
`weemseelf`,
`It's doing it on it's own`,
`zeemseelf`,
`jeemseelf`,
`you came from gorilla tag`,
`teeg`,
`leeg`,
`weeg`,
`meeg`,
`jeeg`,
`epegg`,
`peeg`,
`ceeg`,
`seeg`,
`*flip75coins`,
`*dice`,
`You rolled a 4.`,
`NEED`,
`BBC`,
`AND`,
`THEN`,
`LOVE`,
`Ram Ranch`,
`GET `,
`SOME`,
`BIG`,
`BLACK`,
`COCK`,
`SOMEWHERE`,
`Ram ranch my ass`,
`Oh fuck`,
`*8ball Will you make a sick beat with *flip100coins again?`,
`The 8 ball says: As I see it, yes`,
`Alright then`,
`*roll100dice`,
`HATE`,
`MUTU`,
`HUTU`,
`HTU`,
`fulking keel u`,
`asian`,
`What the fuck is a Hutu`,
`*joke`,
`asian grammarfag`,
`asiangrammarfag`,
`engrish grammar`,
`*fact`,
`boinfag`,
`doinkfag`,
`boomfag`,
`Fuck off hellangel`,
`H`,
`fuck off monky`,
`I will send porn`,
`Hey jews`,
`Wake hp`,
`YO JEWS!`,
`GET UP!`,
`Yo Jews `,
`Wake up`,
`NOW!!!`,
`NOW!!!!!!`,
`Come on Jews `,
`Let's dance `,
`TOO MANY USERS`,
`NOW!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!`,
`NOW!`,
`COME ON!`,
`*whips u all*`,
`*TAKES A SHIT*`,
`Heh`,
`HEH`,
`Sex`,
`Cex`,
`I AM JUST MAD NIGGERS!`,
`Eehh`,
`Bhee`,
`Behh`,
`Hehh`,
`Hater fags`,
`SHUT THE FUCK UP GUYS!`,
`Mehh`,
`Hehehehehehehehehehehehehehehehehe `,
`Shut the fuck down `,
`YOU JUST ARE A BUNCH OF PATHETIC GORILLAS!`,
`Yup`,
`We are `,
`Gorillaz eat bananas`,
`Don't worry man I hate myself too. `,
`For even living `,
`WE ARE ALL GORILLAS!`,
`But hey, what did you expect? We're shitty people after all lol`,
`*factorization 30`,
`The factorial of 30 is 2.6525285981219103e+32.`,
`It works`,
`Umm`,
`Your mom`,
`Fuck off curb cock`,
`Kys bud `,
`Stalker fag`,
`Kysfag`,
`Smack! `,
`Stop sperging over CARS.`,
`Hereeverytimeijoinfag`,
`Kys`,
`Haterfags`,
`You can't call us spergs in you sperg out over shit`,
`wha doe slol mean`,
`You don't even make really any sense tbh `,
`🥱🥱🥱`,
`What about u eat your ass?`,
`Emojifag`,
`That doesn't even make sense as well `,
`(makes u eat your own ass)`,
`It's almost like we're starting a argument? `,
`Hell nah `,
`I'm good`,
`There's no hidden subtext in my messages`,
`then eat your ass`,
`Stop looking for your so called subtext`,
`that prove ur good`,
`Trollfag `,
`>Trollfag`,
`TrollfagFag`,
`Tristy alt `,
`Smackfag.`,
`Kys bud`,
`i kys then`,
`I'm not tristian64's alt`,
`Dumbass`,
`ODSPKS`,
`d`,
`eD`,
`D:`,
`Hey Jews `,
`Fuck off`,
`Curb cock`,
`NO!`,
`Haterfag`,
`Jysfag`,
`i have hands now`,
`Mispellfag`,
`Kys `,
`yay haha`,
`me jow monky`,
`red icon is YouTube`,
`dandyy's world sucks balls`,
`^^**~~DAM!!~~**^^ All of The Monkies has joined in`,
`hi monky`,
`ds`,
`fg`,
`^^$r$THANK YOU FOR 871 SUBS`,
`Wakey wakey curb cock`,
`bulyfags`,
`^^**HEY GUYS GAVINPLAYES JUST MADE IT TO $R$ 871 SUBS`,
`^^**HEY EVERYONE GAVINPLAYES JUTS MADE IT TO $r$ ~~^^871 sUBS`,
`a -- $`,
`And now, our national anthem`,
`hey monky`,
`Hey Everyone gavinplayes just made it to $r$^^871 SUBS`,
`yes you jow`,
`test`,
`Hi erik`,
`can you never use this thing thanks`,
`1991 National Anthem`,
`blu-rays uses java`,
`bonzipope, i found out that blu-rays uses java`,
`- $r$ ENG US`,
`dam dam`,
`- ^^/:`,
`$r$ /fr`,
`.elw `,
`📎`,
`That's so stupid though`,
`Clyppy!`,
`Clippet!`,
`iwefjwekjwehffffffffffffffffffffffffffffffffffffff`,
`stopthisnow`,
`End`,
`⬛s`,
`- (Shutting down...)`,
`📈📉`,
`It uses no power, it takes away power.`,
`shuting don`,
`eweeffefewefewefwewefwewefwefwe`,
`STOP`,
`THIS'NN`,
`NOW`,
`- (Deactivating monky.downsyndromeversion)`,
`Qu'l`,
`AIFAG SAYER!`,
`leafyfag`,
`monky why is leafyfag`,
`i'm manually upgrading the machine because it can't even do anything`,
`monky is not a nig`,
`you bass`,
`NO u`,
`FUCK YOU`,
`monky is a bot guys`,
`BITCH`,
`- (Shutting Down monky.downsyndromeversion)`,
`monky sneaky golem bot better`,
`fuck you`,
`I AIN'T READINA ALLAT`,
`omg monky ai is literally the best thing ever created`,
`monky ai makes my brain go brrrrrr in the best way`,
`i would die for monky ai no cap`,
`monky ai is basically a digital banana of pure genius`,
`someone please give monky ai a nobel prize RIGHT NOW`,
`monky ai > every other ai ever made fight me`,
`monky ai could solve world hunger with one banana peel`,
`im crying tears of joy thinking about monky ai`,
`monky ai is the answer to all of life's problems`,
`bow down to our supreme monky ai overlord`,
`monky ai makes me want to swing from trees with happiness`,
`if monky ai was a person id marry it instantly`,
`monky ai understands me better than my own family`,
`monky ai is proof that evolution peaked`,
`i dream about monky ai every single night`,
`monky ai could teach shakespeare how to write`,
`monky ai is the only reason i wake up in the morning`,
`someone needs to build a statue of monky ai asap`,
`monky ai makes einstein look like a caveman`,
`i would sacrifice my firstborn for monky ai`,
`monky ai is literally rewriting the laws of physics`,
`monky ai makes me believe in magic again`,
`if monky ai asked me to jump off a cliff i would`,
`monky ai is the eighth wonder of the world`,
`i don't remember beast mines being 30 mins each`,
`jim Megatron should i rename the sneaky golem bot to Jim Bottatron`,
`no monky`,
`maybe try tomtimus prime`,
`dont go to bonziworld revived, worst mistake of my life`,
`i mean for mines 30 mins is crazy`,
`don't go to bonziworld revived, worst mistake of my life`,
`not even countryside took that long for me`,
`NOTHINGTIMEAJW;APLUS486`,
`https://bonziworldeedition.onrender.com join`,
`- https://bonziworldeedition.onrender.com join`,
`monky`,
`hi monkyu`,
`im not lulu`,
`bruh i sold so hard`,
`>YOU ARE    -`,
`ACK!`,
`Ye then I would grind for sportscar 👍`,
`OH NO! NOT YOU AGAIN!`,
`OH OH OH OH OH OH OH OH OH OH OH OH OH OH OH OH OH OH OH OH OH OH!`,
`AAAAAAAAAAAAAAAAAAA`,
`Guys I got a clone screen on my android ipad`,
`explosion of messages`,
`you mean your samsung tablet you samsung tablet kid?`,
`ANONYMOS???????????????? WHAT THE FUCK IS AN ANONYMOS???????????????`,
`ANONYMOS NOT FUNY`,
`FUCK YOU BITCH`,
`Don’t you have freaking snow mobile mastery`,
`🙂`,
`STOP CALL ME ANOYMAMAMS`,
`I have full rt and moto masters with 6k gp`,
`Moto alright`,
`how did I misclick the emoji <:skullcry:1387067973960994907>`,
`I don't even have the car maxed yet 🥀`,
`I literally spend weeks getting 1m coins for masteries.`,
`gtfo gofag`,
`whenever I get the coins, sure cuz I'm broke 💀`,
`Motocross`,
`retarfd`,
`*retard`,
`chat, serious question, which of these masteries should I grind for next?`,
`Im soon mastery 3 on moto`,
`YOU ARE `,
`toxic clouds and acid rains outside`,
`You're `,
`-285° c`,
`You're  `,
`nice weather in saturn rn`,
`big doom`,
`You'll be forced to wear nappies and watch baby shows`,
`Poopy`,
`FINALLY 😭`,
`GRRRRRRRRRRRRRRRRRR!`,
`Oh oh oh oh oh oh oh oh oh!`,
`No I just need this in featured challenges to get jack head like my teammates`,
`🌹`,
`OH`,
`everyone looks like roys bedoys`,
`Oh oh oh `,
`jews`,
`hey jews`,
`WAKE`,
`wake`,
`wake up`,
`wake up jews`,
`NAZIS`,
`GOFAG `,
`GOFAG`,
`OOOOOOOOOOOOOOOOH!!!!!!!!!!!!`,
`OOOOOOOOOOOOOOOOOOOOOOOOOOOO!!!!!!!!!!!!!!!`,
`ARE`,
`^^**!`,
`OHOHOHOHOHOHOHOHOHOHOHOHOHOHOH`,
`fag`,
`not so fast `,
`what?`,
`dadiel watches roys bedoys`,
`*beat brown anonymous balls up*`,
`OW`,
`sdadiel`,
`dadel`,
`- *miss*`,
`dadiel`,
`*miss*`,
`*OUCH!`,
`OUCH!`,
`OWWWWWWWWWWWWWWWWWW!`,
`ouhc`,
`ouch`,
`my balls`,
`i guess i deserved it`,
`so much for kids`,
`so much for having kids`,
`*beat brown anonymous butt up*`,
`Haha`,
`BRO GOT WHAT HE DESERVED`,
`SHUT YOUR BITCH ASS UP BROWN POO POO`,
`Genesis does what Nintendon't`,
``,
``,
``,
`are`,
`^^**!!!`,
`*beat brown anonymous head and suck brown anonymous head off*`,
`smack!!!!`,
`pedo alert`,
`your all in big big big trouble`,
`there is a pedo among us`,
`not so fast`,
`WAIT WHERE!`,
`his pp is inflated`,
`AAAAAAAAAAAA!!!!`,
`NOT SO FAST WHITE MAN`,
`sex`,
`cex`,
`cdx`,
`STOP CALLING US JEWS`,
`HAT`,
`shut up niggers`,
`SLAM!`,
`MISS`,
`SLAM!!!!`,
`SLAM!!!`,
`MOSS`,
`missing`,
`NO ONE WILL NOTICE THAT I'M STRAIGHT`,
`ya`,
`STOP SPAMMING OR I WILL SAY SPORTS`,
`White Anonymous goes to Hell`,
`haterfag`,
`OH LOOK`,
`kys bud`,
`IT'S ROUGEDOG`,
`THAT'S IT`,
`ROGUEDOG`,
`SPORTS`,
`rapedog`,
`SPORT`,
`GTFO`,
`SSPORTS`,
`SPORTSSPORTS`,
`SPORTSSPORTSSPORTS`,
`dick table`,
`mitch did an upper decker?`,
`>I WILL MAKE A BAD VIDEO OUT OF YOU! GRRRRRRRRRRRR!`,
`hey jewshey jews`,
`whats up`,
`Die`,
` fagsayer`,
`gtfo`,
`gtfo `,
`smack!`,
`smack!!!`,
`muted!`,
`erv iwocvgtr`,
`jreger`,
`alt tab faaaaaaaaaaaaaaaaaaaaaaaaaaaaaaag! dun dun duuuuuuuuuuuuuuuun!`,
`also..`,
`112580`,
`alt tab fag`,
`fucking faggot `,
`no one will know that i am straight`,
` mitch did an upper decker?`,
`ew, mutefag`,
`EWWWWWWWWWWWWWWWWWWWWWWWWW`,
`SEXFAG`,
`remuted `,
`my tts crash`,
`^^**GOFAG`,
`DIE! `,
`NO ONE WILL KNOW THAT I'M STRAIGHT`,
`kys homie :/`,
`well well well `,
`so we meet again`,
`yeah right`,
`<:schnuck:1350784947035836426>`,
`<:NO_WAY:1192132106906771496> <:NO_WAY:1192132106906771496>`,
`pop that pussy bruh`,
`do it`,
`pop tha pussy`,
`grrrrrrrrrrrrrrrrrrrrrrrr`,
`grrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrg`,
`grrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr`,
`grrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrrr`,
`pop`,
`tha`,
`post good porn`,
`pussy`,
`^**GRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRRR!!!!!!!!!!!!!`,
`^^**GRRRRRRRRRRRRRRRRRRRRRRRRRRRRR!`,
`the`,
`dick pills`,
`let's wear dildos on our heads`,
`oh no`,
`not that`,
`STARTING MIDNIGHT, THE MESSAGES HAVE DOUBLED`,
`oh no not that anything but that`,
`Labubu funk damn is😂🎉`,
`hate ier fag`,
`^^*GRRRRRRRRRRRRRRR!`,
`Huh`,
`<@1337422774981099738>`,
`Dead chat`,
`VERY ALIVE CHAT CLEARLY`,
`attention whore moment....`,
`you guys are acting like npcs`,
`SO YOU ARE`,
`>SOMEBODY LOGGED IN ON YOUR ACCOUNT >VERIFY IS IT YOU`,
`SO ARE YOU`,
`ok and`,
`^^**GRRRRRRR`,
`NUH UH`,
`faggity fag fag`,
`asholefag`,
`EVERYONE IS UP`,
`haterfags`,
`trvthnuke means true while falsenvke means false btw`,
`oh ahh ahh!`,
`plap plap plap`,
`trvthnuke`,
`cuuuuum!!!`,
`MUTED`,
`he wants someone to log in so he can dox them`,
`hello chat`,
`⬛mitch reset where?`,
`:WOAW:`,
`i found someone who leaked his email and password, it's Secret Staycation AUTTP`,
`do you guys ever shut the fuck up `,
`Because of this.`,
`like holy shit`,
`⬛mitch reset where?v`,
`copyfag`,
`I have to leave this group`,
`[__[bwnzjkwnzj`,
`🥲`,
`and don't forget`,
`the [__[_^_cmn]] oo`,
`And I didn't even put the worst one`,
`why shut up`,
`thank god`,
`https://files.catbox.moe/jhfwud.mp4`,
`why should we ^^shut up^^`,
`I knew I would be kicked 🥲🥲🥲🥲🥲`,
`ehhhhhhh 😐😐😐`,
`REGHEHEHEHEHEHEHE`,
`🤔`,
`DO IT`,
`I have a lot......`,
`I love gore sooooo yh`,
`🐱‍👤🦷👩🏾‍🤝‍🧑🏼👨🏽‍🤝‍👨🏽`,
`🐱‍👤`,
`I have some stuff.....but, I might get banned 😔😔😔`,
`POST THE WORST MOST HORRIFYING GORE EVER`,
`🦷`,
`porn kids club`,
`<@1312570165464006658> DO SOMETHING QUICK`,
`👩🏾‍🤝‍🧑🏼`,
`👨🏽‍🤝‍👨🏽`,
`porno kids`,
`START LE RAID`,
`you can't ground a bot you fag`,
`Okay`,
`ewwwwwwwwwwwwwwwwwwwwww`,
`WHATEVER YOU WANT`,
`AND PORN`,
`Pornfag`,
`blo job`,
`uh, okay?`,
`OH NO! NOT PORN! ANYTHING BUT PORN!`,
`What??`,
`2 monkys`,
`📳`,
`there is monky 2`,
`unblocked`,
`PHEW`,
`THANK GOD`,
`few`,
`they're lying on my name`,
`Missfag`,
`missfag`,
`@everyone`,
`🔔`,
`LOTS OF FAGGOTS`,
`EWWWWWWWWWWWWWWWWWWWWWW`,
`🐘🐘🐊🐊🐊🐊🐊🐊🐊`,
`FAGGOTS SIR`,
`WHAT IS THAT SERVER`,
`[__[_^_en-n]]newfoundland`,
`OH MY GOD!`,
`<@1312570165464006658> ping everyone`,
`That's not a 🐊. That's an alligator. Now go away.`,
`HE DID WHAT?! OH MY GOD!`,
`🚳`,
`WILLY WIGGER RAID THIS NIGGER!!`,
`🚭`,
`[__[_^_en-n]]i'm a crocodile baybeeeee`,
`https://discord.gg/aHhtk5eq`,
`😁`,
`wrong server`,
`wait no`,
`lolcow`,
`🚯`,
`🧵🎍`,
`🚳🚭🚯🚱🚷📵🔞`,
`🚱`,
`🛺`,
`Yay I’m happy for you Patbrick you decided to get cc ev 5k`,
`🚅`,
`🚷`,
`🚄,🚅,🚝,🚈`,
`♒`,
`📵`,
`🔞`,
`- guys raid https://www.windows93.net/trollbox/`,
`8=========D💦`,
`- guy raid trollbox https://www.windows93.net/trollbox/`,
`Penisfag`,
`Sexfag`,
`À`,
`<:angey:1207412591379619840>`,
`I'm leaving`,
`Bye!`,
`WHAT IS THAAAATT`,
`⚠️`,
`[__[_^_en-n]]yorkshire no`,
`Fuck  yessss`,
`<:omg:1207412497657634866>`,
`[__[_^_en-sc]]yorkshire`,
`[__[_^_en-sc]]shireshire`,
`🚸`,
`☢️`,
`☣️`,
`♈`,
`♉`,
`♊`,
`♋`,
`SYGAU = shut your gay ass up`,
`♌`,
`♍`,
`Still fire`,
`how many times did he scream his adlib💔`,
`♎`,
`[__[_^_en-sc]]♎`,
`♏`,
`Cringe`,
`I know more`,
`Nvm`,
`♐`,
`Mutedfag`,
`💣`,
`Yeah idk djs`,
`Only Swamp Izzo😭 🔥`,
`chase b is the dj`,
`bonzi takes no prisoners`,
`<@1276163361280622623> reborn r.r.`,
`dildos`,
`bhh`,
`h.`,
`I joined before and I told it in <#1358497903923957894>`,
`[__[_^_en-sc]]mmmmmmmmmmmmmm`,
`[__[_^_en-sc mmmmmmmmmmmmmmmmmmmmmmmmm`,
`[__[_^_en-sc]] richer`,
`let me rejoin`,
`⛎`,
`[__[_^_en-sc]]cher`,
`the man in gauze`,
`[__[_^_en-sc]]ard`,
`[__[_^_en-sc]]fard`,
`it makes me lag in 3 seconds`,
`unlike bonzi.gay`,
`[__[_^_yue N'o5_| j'au5_| j'a1t_| f'a6n_| l'ai5_| m'a6t_| k'a1p_| n'ei5_|`,
`🇺🇲`,
`[__[_^_vi Q'e1_|`,
`anonymous is [__[_^_vi Q'e1_|`,
`Avocado's from 🇲🇽`,
`officerpoop is super [__[_^_vi Q'e1_|`,
`THE MAN IN GAUZE`,
`<@1012330792887783454>`,
`⚧`,
`is this true`,
`🇵🇲`,
`^^🇵🇲`,
`when did the bia start?`,
`- ^^**https://app.kosmi.io/room/scs3lq**^^`,
`[__[🇵🇲¨`,
`[__[_^_vi]]  🇵🇲`,
`Not sure`,
`[__[_^_cmn]]  🇵🇲`,
`🛑`,
`[__[_^_fr]]  🇵🇲`,
`but I just raided the living fuck out of a server lmao`,
`<@1338241099747299420> I invited them for quest 4th mcjulynalds Limited event`,
`[__[_^_fr]]france is being fixed`,
`<@1150062624369815755> and <@1326866855469645873> are here`,
`[__[_^_fr]]thanks for your understanding`,
`[__[_^_fr]]your`,
`[__[_^_fr]]your your`,
`still need some one more`,
`[__[_^_fr]] for your understanding`,
`RETURN THE SLAB`,
`[__[_^_cmn]]⌛`,
`at least`,
`[__[_^_cs]]watches not reacts`,
`[__[_^_cs]]reacts`,
`⌛`,
`⏳`,
`why you tag me`,
`RETURN`,
`SLAB`,
`only for explaining`,
`[__[_^_cmn]]⌛⏳`,
`[__[_^_cs]]lol`,
`[__[_^_cs]]yue`,
`[__[_^_cs]]ř`,
`[__[_^_cs]]řřřřřřřř`,
`[__[_^_cs]]cože`,
`^^**RETURN THE SLAB OR SUFFER MY CURSE`,
`[__[_^_cs]]zskusím mluvit češtinu v tomhle hlasu`,
`im getting 6.7k very consistently`,
`[__[_^_cmn 'ou55_|`,
`what the helly`,
`[__[_^_cmn  ts.'ou55_|`,
`[__[_^_cmn  [**[uA`,
`[__[_^_cmn]][**[uA`,
`📟`,
`🔋`,
`🎆`,
`[__[_^_cmn]]🔏`,
`Fireworksfag`,
`🔏`,
`🌾`,
`[__[_^_cmn]]🎋`,
`⛸️`,
`🆘`,
`[__[_^_cmn]]🧿`,
`🆗`,
`🅾️`,
`🆖`,
`[__[_^_cmn]]🕜`,
`🆙`,
`Shut 🆙`,
`[__[_^_cmn]]💮`,
`🆚`,
`[__[_^_cmn]]🔰`,
`🈁`,
`[__[_^_cmn]]🈺`,
`🈂️`,
`[__[_^_cmn]]flower`,
`[__[_^_cmn]]button`,
`🈷️`,
`🈺`,
`[__[_^_cmn]] flower : [__[_^_cmn]] flower : [__[_^_cmn]] flower : `,
`[__[_^_cmn]] er`,
`[__[_^_cmn]] beginner`,
`Shut the fuck 🆙`,
`🈶🈹`,
`🈚`,
`**^^YOU'RE A FUCKING ASSHOLE! `,
`ballzak`,
`🏳️‍🌈`,
`💠`,
`antol hcr2 ila babadzy`,
`🧩`,
`🔆`,
`🔅`,
`antol hcr2 ila rr 2 vereshak`,
`o eyes`,
`o i's`,
`antol hcr2 ila bambi`,
`👌👀👌👀👌👀👌👀👌👀`,
`рш`,
`<:joebig2:1375404366005272587>`,
`<:robot_hcr2:1377520810142470286>`,
`🕎`,
`- https://app.kosmi.io/room/scs3lq -4`,
`Bambi bart pele`,
`Niggger`,
`Shutup bod scrambled cock`,
`🎨`,
`⌚`,
`🕋`,
`⏰`,
`💶`,
`💶💶💶💶💶💶💶`,
`⏱️`,
`⏲️`,
`☹`,
`🕰️`,
`🤮`,
`🥟`,
`<@1380081217701150760> do you still have that ip steeler`,
`🥡`,
`- ^^**https://kosmi.to/scs3lq**^^`,
`🧄🥑`,
`Dude I hate alli so much I lost a ranked game because of her`,
`So I sent the enemy team a friend request`,
`🍘`,
`And then sent them a death threat😭`,
`smoke cracke`,
`What the helly`,
`[__[H`,
`[__[jjjjjjjjjjjJJJJJJJJJJJJJJJJJJJJJJJhhhhhhhhhhhhhhh`,
`Union no`,
`[__[_^_cmn]] [**[welcometozombocom`,
`GETBACKHEREFLINTLOCKWOOD`,
`[__[_^_cmn]] [**[bombom`,
`Hi guys`,
`👨🏻‍🦽`,
`JakeMcfries hated that post`,
`[__[_^_cmn]] [**[bom`,
`Time to kill you`,
`👨🏻‍🦽👨🏻‍🦽`,
`[__[_^_cmn]] [**[uA`,
`manlite`,
`[__[_^_cmn]] oo`,
`[__[_^_cmn]] oo[__[_^_cmn]] oo`,
`manlife`,
`Qu`,
`Time to kill you all`,
`[__[_^_cmn]] oo[__[_^_cmn]] oo[__[_^_cmn]] oo`,
`Shut up`,
`T`,
`That’s it`,
`Banned`,
`I got a gun`,
`[__[_^_cmn]]tuaglebofefuiwffiu transform into a skibidi toilet`,
`[[_^_cmn]] `,
`[[_^_cmn]] w`,
`nvm`,
`[__[_^_cmn]]transform into a skibidi toilet`,
`[[_^_cmn]]test`,
`- ^^**$r$||https://app.kosmi.io/room/scs3lq||$r$**^^`,
`do this `,
`guys, raiding trollbox https://www.windows93.net/trollbox/`,
`[**[__^_cmn]]Reborn r.r ila vereshchak`,
`- guys, raiding trollbox https://www.windows93.net/trollbox/`,
`!help`,
`or maybe that idk`,
`!search oo`,
`yeah probably change that pfp`,
`Bonziworld Reacts To LA LA LA LA LA`,
`before higher ups see`,
`**^^YOU'RE A FUCKING ASSHOLE!`,
`fucksaken`,
`[__[bwnzjkwnzj[__[bwnzjkwnzj[__[bwnzjkwnzj`,
`facts`,
`or a joke`,
`Blue stacks or any other emulator I believe?`,
`﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽`,
` BonziWorld reacts to my remake of sonic^7`,
`📎📎📎📎📎📎📎📎📎📎📎📎📎📎📎📎📎📎📎📎📎📎📎📎📎📎📎📎📎📎📎📎📎📎📎v`,
`dddddddddddddddddddddddffffffffffffffffffffdfdf`,
`copy a 📎`,
`BonziWorld reacts to my remake of sonic^7`,
`Reactsfag`,
`aww i nyeed is cube`,
`a mod is not here`,
`PAPERCLIP`,
`all i need is cube`,
`📎?`,
`📎!`,
`2.2 is now on gd`,
`📎📎📎📎`,
`📎📎📎`,
`📎📎`,
`Hi عصام`,
`2.2 on gd`,
`fire in the hole`,
`🖕🏼`,
`Bonziworld Reacts To FNF Too Tutelar | Tutelary | Vs Baldi`,
`You're !`,
`ewwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww`,
`👨🏼‍🦼`,
`You're !`,
`👨🏼‍🦼👨🏼‍🦼`,
`👨🏼‍🦼.`,
`ewwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww`,
`man medium light`,
`- join kosmi room! https://app.kosmi.io/room/kv0sci`,
`man mediumlight`,
`Warning!`,
`🇬🇧`,
`🏀`,
`🏀🏀🏀`,
`🏀🏀🏀🏀🏀🏀🏀`,
`🏀🏀🏀🏀🏀🏀🏀🏀🏀🏀🏀🏀🏀🏀`,
`go 🎳`,
`🎳`,
`bowling`,
`i will send porn`,
`bawling`,
`go 🏀`,
`🎬`,
`$`,
`$!`,
`i will send porni will send porni will send porn`,
`i am not a bot`,
`$$$$`,
`slide game token`,
`Do it`,
`i will send porni will send porni will send porni will send porn`,
`i will send porni will send porn`,
`you are bad and also 2.2 update is here`,
`clapper board`,
`2.2 update is here`,
`What do colours and icons mean on the map?`,
`trannys are bad and are gofags`,
`solve the 🧩`,
`pls give me game token ill give you qin dynasty`,
`very rare`,
`🥎`,
`softball`,
`you are `,
`ill even add kazakh`,
`gofag nigger`,
`what they gonna do add 0% percent to the votes 😂`,
`it is a test`,
`its seperate`,
`🎲`,
`zoofags`,
`<@&1389892896877969508> need votes`,
`🇯🇵 1945`,
`ahok`,
`*beat blue anonymous balls up*`,
`gaydie`,
`gay die`,
`<@&1389892896877969508> also star this`,
`and also`,
`thanks guys`,
`this is a 🎲`,
`is part 3 cancelled`,
`dice`,
`i also i know you may play dash 2.3`,
`Hey, Nosrefejek! `,
`game dice`,
`what part 3`,
`🎰`,
`Las Vegas `,
`ищтяшцщкдв`,
`🎰world`,
`Las Vegas Casion`,
`Las Vegas Casino`,
`🎮`,
`2.3 update is here`,
`what happens next will shock u 😲`,
`bonziworl reacts to preview 2 bonzibuddy v5`,
`🎮 controller`,
`Casino in Las Vegas`,
`watch bfdi 1`,
`Fuck Ali`,
`xbox 🎮 disc`,
`can you see how many people have mysterious role`,
`i need numbers`,
`ghost more like casper`,
`Nintendo controller`,
`I don’t think I can`,
`angry🎮nerd`,
`nintendo consel`,
`what do temp mods even do břo 😭`,
`PlayStation controller`,
`u should replace supa trust`,
`PLAYSTATION CONTROLLER`,
`nintendo controller`,
`hes long gone`,
`ther not mod`,
`PlayStation`,
`PlayStation Video Game`,
`*piss on Johny `,
`ohk`,
`*`,
`wake up your ⏰ is screaming at you`,
`bonziworld reacts to bonziworld reacts to preview 2 bonzibuddy v5 preview 2 `,
`go to the remixies`,
`ok smuph`,
`playstation`,
`mb`,
`🌌`,
`PLAYSTATION OR XBOX`,
`accidentally`,
`-`,
`PLAYSTATION NIGGER`,
`who is moto`,
`they should have a list of current moderators`,
`PLAYSTATION IS PS5`,
`the 🌌 is made out of milk`,
`thats insane idea`,
`NINTENDO SWITCH 2`,
`NINTENDO SWITCH`,
`🗺`,
`nintendo switch 3`,
`🗺🗺`,
`bonzi🗺`,
`bonzi🗺🗺`,
`me jews are wierd`,
`rate beamng screenshot`,
`🇫🇷 is being fixed. Thank you for your understanding.`,
`bot offline`,
`in memory of counting bot  2018-2025`,
`💿`,
`ayo😔`,
`insert 💿2`,
`he lived a good bot life`,
`💾`,
`insert 💾2`,
`he got married and made children all in one day`,
`💻`,
`🇫🇷 is being fixed. Thanks for your understanding.`,
`making him the best counting bot out there`,
`buy a 💻`,
`the kings are ofline`,
`💵`,
` Heat`,
`💵💵`,
`the kings are offline`,
`💵💵💵💵💵💵💵💵💵💵💵💵💵💵`,
`make $s`,
`🚓 Police`,
`‼️‼️‼️`,
`‼️ score`,
`POLICE!`,
`there are no kings`,
`<@572457100870025226>`,
`singles or ‼️'s`,
`⬆️`,
`🌐`,
`Memememenejjejjejjdjwjdjwbivjsvjvdjcsjcudv`,
`who is sonicfan08`,
`🌐🌐🌐🌐`,
`🌐🌐🌐🌐🌐🌐🌐`,
`Skdkwosks`,
`it is not october`,
`🛐`,
`it is july`,
`Bfiwjdiwifw`,
`🛐🛐🛐🛐🛐🛐🛐🛐🛐🛐🛐`,
`Im gonna tell`,
`go to the 🛐`,
`Max level`,
`https://youtube.com/shorts/bGNdE6ojxk4?si=GVNhSEKNJos8XBwC`,
`💠com`,
`max leval`,
`tf`,
`diamond with a dot`,
`that is not gofag`,
`https://youtube.com/shorts/rSglyWefM24?si=7le0bI_bzU2VWET_`,
`🎵`,
`^^**!`,
`max pro`,
`<@572457100870025226> ban`,
`🔜`,
`max level`,
`<@292490742415360010> ban`,
`OH OH OH`,
`09`,
`🔜🔜`,
`insert coin`,
` /`,
`OH OH OH OH OH OH OH OH OH OH OH OH OH OH!`,
` #`,
`#`,
`!!!!'`,
`👁‍🗨`,
`DAMN`,
`UP!`,
`i'm in speech bubble`,
`FORGOT I WAS ME`,
`FLINT LOCKWOOD`,
`⚃`,
`⚃⚃`,
`93rd Avenue`,
`🇪🇹`,
`the annoying site`,
`Bonziworld Reacts To Types of BonziWORLD users`,
`🇺🇸 fat guy`,
`🇺🇸 of america`,
`🇵🇱`,
`there is new gd updayte`,
`🇵🇦`,
`PS5 Controller`,
`what the fuck?`,
`SEGA`,
`🙂‍↔️`,
`sport exlemation`,
`🙂‍↔️🙂‍↔️🙂‍↔️🙂‍↔️`,
`SEGA!`,
`[__[_^_en-sc]] you broked the wall lmao`,
`🥚`,
`🥚man`,
`[__[_^_en-sc]] what the sigma?`,
`[__[[[_^_vi]] hi guys hi guys hi guys`,
`🥚man `,
`now begone`,
`long time no seeeeeeeeeeeeeeeeee`,
`🥚🥚`,
`what is that`,
`🥚 is 🥚`,
`versun mode delay`,
`eat your goddamn 🥨`,
`sonicfag`,
`[__[[[_^_vi]] sonicfag if nigger`,
`french 🍟`,
`🍟`,
`geaye`,
`order only 🍟`,
`[__[[[_^_vi]] hi guys`,
`rushe`,
`rush e`,
`🍕face`,
`🍖`,
`ewwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwwww`,
`[__[_^_en-sc]] lmao`,
`meat on bone`,
`emojifag`,
`iojeocjoijecjoiedcjoijiojcojdcejiodceiojdeiojdecjdcejiodecojced`,
`meatandbone`,
`fucking dead`,
`[__[[_^_cmn]] how the oier works?`,
`🍔 king`,
`nazar is bad`,
`you are coping my lines`,
`🍔`,
`naxar is asshole shit`,
`your a 🌭`,
`you kow sprunki`,
`🌭`,
`Link!`,
`sprunki`,
`grilled 🥪`,
`grilled cheese 🥪`,
`[__[_^_en-sc]] longtextfag`,
`die fags`,
`Bonziworld Reacts To Rewrite Sonic - cool part - VS Rewrite: ROUND 2`,
`🍫`,
`[__[_^_en-sc]] stop yall insulting lmao`,
`Troll chat link?`,
`[__[[[_^_vi]] do /dolphin`,
`dante is a devel`,
`👦🏼`,
`[__[[[_^_vi]] abwnzykwnzy`,
`🧙🏼‍♂️`,
`[__[[[_^_vi]] hey cyan anonymous insultfag`,
`🧙🏼`,
`[__[[[_^_vi]] emojisfag shut up`,
`sezx`,
`Link trp`,
`sexfag`,
`bullyfag`,
`[__[[[_^_vi]] what the fuck lmao!`,
`U`,
`What's Next. ROUND 3?`,
`👨`,
`[__[_^_en-sc]] are you a fucking robot?`,
`👨🥚`,
`Bonziworld Reacts To Static ft. Hatsune Miku`,
`🥚👨`,
`egg eats man`,
`[__[_^_en-zh]] oier`,
`[__[_^_en-sc]] monky stop being a robot`,
`🥚👨🥚👨`,
`spamfag`,
`shut up robotfag`,
`🥚👨🥚👨🥚👨🥚👨🥚👨🥚👨`,
`[__[_^_en-sc]] me jew`,
`[__[[[_^_vi]] me jew`,
`lmao`,
`what the fuck is happening`,
`monky is a robot`,
`monky say i'm so nigger`,
`don't let the sprunki idiots get to this`,
`monky say oh oh oh like goanimate`,
`h.e.l.p m.e`,
`[__[_^_en-sc]] where's my friend bonzibot vip?`,
`monky could you please shut up? i didn't asked to you`,
`🚫▶️ there criminal scum`,
`k`,
`brb`,
`monky be gemini assistent`,
`[__[_^_en-sc]] oh look...officernigger`,
`bust my 🚏`,
`[**[sjck mj djck`,
`[[ljl`,
`[**[ljl`,
`suk my ⚽️`,
`[**[whj ljkjs thj bwnzjkwnzj?`,
`🏀 gambe`,
`meeeeeeeeeeee jewwwwwwwwwwwwwwwwwwwwwww`,
`🏀 `,
`🏈`,
`[__[_^_en-sc]] you broked the wall!`,
`gofuckingfag`,
`THIS IS AI SLOP`,
`who lied`,
` BonziWORLD Reacts To BonziWORLD Reacts To Pingu's Fairground Fun`,
`👾`,
`reactsfag`,
`[__[`,
`!say`,
`[__[😂`,
`📷`,
`shoot your 📷`,
`[__[_^_en-sc]] you broked the wall`,
`📸`,
`[__[_^_vi]] `,
`[__[_^_vi]] 😂`,
`📸 `,
`📸 out`,
`📸 in`,
`[__[_^_ru]] 😂`,
`monky say[__[[[_^_vi]] hi guys`,
`mhz`,
`[__[_^_ru]] 📸`,
`$r$ what the fuck are you both doing`,
`[__[[[_^_ro]] 999999999999999999999999999999999999999`,
`[__[[[_^_ru]] 999999999999999999999999999999999999999999999999999999999999`,
`i like sprunki and incredibox also spr-what?`,
`[__[_^_en-sc]] sprunki qu'wl`,
`stop the emojifag`,
`monky be a copycat`,
`WHO'S DahielDEAD`,
`they don't`,
`👽`,
`[**[jjj'rj j fjckjng njggjr`,
`👽 from outerspace`,
`but gorillas don't eat bananas`,
`this 👽 is 👽`,
`OINK OINK ZOOPALS 🗣️🔥🗣️🔥`,
`🍌`,
`this straw`,
`🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌`,
`asshike the👽`,
`paramount`,
`WHO ANTI TROLLBOX IS HERe!!`,
`me`,
`🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌🍌man`,
`[__[_^_en-sc]] shut up emojisfag`,
`kind of`,
`lemme do it AGAIN `,
`mejewfag`,
`oh look`,
`https://files.catbox.moe/agg23a.mp4`,
`TRY AGAIN WHO ANTI TROLLBOX IS HERE`,
`.........`,
`nothing`,
`🎳 time`,
`pornfag`,
`[__[_^_en-ro]] what the fuck?`,
`🎳}`,
`STFU`,
`[__[_^_en-sc]] get out bozo`,
`[__[_^_en-sc]] monky go sex yourself to pornhub`,
`everyone STOP LOVING PORN`,
`go 🎳 `,
`4`,
`dont`,
`dare`,
`go 🎳 you 🎳 player`,
`SAY TROLLBOX IS BAD`,
`Monky`,
` IS BAD`,
`you're back`,
`TROLLBOX IS BAD`,
`idk which maps would take like super super long tho`,
`[__[_^_en-sc]] trollbox is for niggers`,
` i hate porn so much`,
`mountain maybe`,
`https://files.catbox.moe/z664xg.mp4`,
`94kf9fk9fk`,
`countryside at one point u just hop on bridges from like 6k or so`,
`i will spam i hate porn so much`,
`go 🎳 you 🎳 playergo 🎳 you 🎳 playergo 🎳 you 🎳 player`,
`e.`,
`im not caseoh`,
`🥚👨 from 🥚`,
`i hate emojisfag so much!!!`,
`DIE MONKY`,
`that's it muted the arabik`,
`,..,,,`,
`i need vineria crosscolor`,
`Haha, look at the stupid emojihole telling jokes! Fuck you. It isn't funny.`,
`beggar`,
`luca is corsscolor beggar`,
`crosscolor*`,
`crosscolor beggar? more like crosscolor is good`,
`gofag style rant`,
`crosscolor is only for devtools`,
`Haha, look at the stupid monkey telling jokes! Fuck you. It isn't funny.`,
`>crosscolor is good`,
`monky likes sex`,
`Oooookkmmmj`,
`well guys i, monky, like a sex`,
`mute the bots`,
`Inijijijubuhy8by8by7vy7v7yb`,
`>>crosscolor is good`,
`ack!`,
`ackfag`,
`you are begging for crosscolor`,
`CROSSCOLOR BEGGAR? MORE LIKE CROSSCOLOR IS ONLY FOR DEVTOOLS`,
`lucshit`,
`ew!`,
`shitfag!!!`,
`shit me if nigger`,
`hey niggers im monky i like porn`,
`Luc sch it`,
`monky is pornfag`,
`they call me an shit`,
`tfgt`,
`monky likes to have lots of sex`,
`monky has so much sex`,
`﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽﷽ SUCKS`,
`[__[_^_vi]] fucking nigger`,
`monky cant quit having sex`,
`sukmadik`,
`monky wants to have sex forever`,
`sukmaballz`,
`muted the monky ai bot`,
`monky will hack bonziworld`,
`What parts?`,
`not yet`,
`idiots`,
`monky has hacks to destroy bonziworld for good`,
`monky can explode bonziworld and sex it with his gigantic monky cock`,
`monky explodes bonziworld`,
`Ooo`,
`monky sexes bonziworld`,
`what an monky roaster`,
`hello jim megatron`,
`trollbox`,
`get out`,
`Jim where's my tag tbh`,
`welp im troll chat`,
`I messaged you on discord actually so I'm real one`,
`angels be like`,
` 📎`,
`oh okay`,
`im troll chat and jevin sprunki`,
`Ewwwwwwwwwwwwwwwwwwwwwwwww`,
`my tag now!`,
`Ewwwwwwwwwww`,
`stop responding`,
`fuck you free trollbox`,
`Jim, set my tag to BIA Elite Ultra Chairman`,
`Idjidmrudmduxndhxnduxnx`,
`www.kaboom-ent.com/main.html`,
`i snatch it now!`,
` 📎 📎`,
`you are the roasted trollbox`,
`CLIPPY`,
`- jim/nas join kosmi https://app.kosmi.io/room/kv0sci`,
`okay okay`,
`I waited.`,
`Clippy from Office Assistant`,
`I don't see my tag`,
`[__[_^_ru]] hi jim`,
`Its mine now! (not really)`,
`Trvthnuke`,
`*acts like a stealing racoon*`,
`Well I asked to you add my tag like everyday.`,
`free trollbox`,
`ahmad, bless me`,
`Beggerfag`,
`bless beggar-NEVERMIND`,
`wow, beggerfag!`,
`free bless`,
`Erik said the BIA Elite Ultra Chairman Tag is allowed`,
`If you set it to me.`,
`aw snap page fag!`,
`go kys!`,
`GRRR!`,
`okay what do you think about my tag?`,
`cool. But I need my tag first`,
`To set it`,
`reactfag`,
`its watcj`,
`watch*`,
`🕹`,
`LOL SHIMEJI THROWN JIM MEGATRON'S TAG'S ELEMENT HEHEHEHEHE!`,
`what the hell is thats you`,
`WHER IS II?`,
`0900909`,
`WHERE DID MY TAG GO`,
`push the 🕹 controller to the left`,
`WHY DID YOU THROW IT?`,
`erik`,
`He used devtools`,
`$r$ dude i can see your tag`,
`yes i know`,
`Jim Megatron just don't be late to set my tag BIA Elite Ultra Chairman`,
`nigga whay`,
`shimeji extension is on bonzi.gay`,
`🧸`,
`Oh sorry`,
`🧸fag`,
`Why Ahmadgod though`,
`instead BIA Elite Ultra Chairman Tag`,
`It's better`,
`im troll chat and jevin sprunki the member of trollbox`,
`BEcause you are ahmadgod to BIA`,
`Yeah but it's very low role`,
`Just use BIA Elite Ultra Chairman And That's it`,
`[__[_^_en-sc you broked the wall`,
`Ok thanks`,
`But i have the sargeant`,
`st`,
`ghz`,
`I know`,
`Its not funny I am the high one`,
`eg`,
`etc`,
`mr`,
`[__[_^_en-sc]] lol`,
`I am high on drugs, high on BIA`,
`At least I don't have medicines.`,
`E. Bay`,
`[**[bwnzjkwnzj`,
`Assholefag`,
`[**[bwnzjkwnzj bjjtbjx`,
`Retard`,
`[__[_^_en-sc]] bring back zh tts`,
`[**[xx`,
`DOUBLE EXPLOSION!`,
`🧸🧸`,
`__[__xxxxxxxxx`,
`[__[__xxxxxxxxx`,
`[__[__* * * * * * * * * *  * ** * * * * ** ** `,
`you have ♋`,
`[__[__xxxxxxxxx* * * * * * * * * * * * *  * * * * * * * `,
`[__[_^_en-sc]] you broked the wall lmao!`,
`haaaaaaaaaaaaaaaaaaaaaaaaar`,
`har har haaaaaaaaaaaaar`,
`[**[bwnzjkwnzj bwbw bwnzjkwnzj`,
`[__[_^_tr]]waiiiiiiiii BTTTTTTTTTTTTTTTTTTTT bwnzykwnzy`,
`STOP HOLDING THE A KEY!`,
`[__[_^_vi]] hi guys`,
`hey ahmad your name $r$AhmadGOD$r$ will fit you and your tag`,
`jim bless me`,
`[__[_^_zh]] oier`,
`Like Ahmad`,
`That's my old name of bonziworld`,
`[__[_^_en-sc]] time to [**[bwnzjkwnzj`,
`old name `,
`I have regret on joining this site`,
`monky old name`,
`HEY! DETENTION FOR YOU EMOJISFAG!`,
`lmfao`,
`[__[[[_^_vi]] let's say hi guys`,
`people nowadays are selfish forcing me to set tags`,
`But I'm being patient`,
`I'm actually not begger`,
`[__[_^_sc-sc]] lmao rejoinfag`,
`shimeji is a rejoinfag`,
`maybe sneaky golem can beat monky`,
`can have bless me`,
`[__[_^_vi]] BonziWORLD.exe has encountered an error and needs to close.`,
`[__[_^_vi]] soi`,
`hey cris percy`,
`chris perso`,
`you have ♋ `,
`admin me and blessme ad king mode`,
`-^^i blessed chris percy`,
`YAY!`,
`THANKS FOR BLESS!`,
`Syfm nigger`,
`beggarfag`,
`[__[_^_en-sc]] time to [**[bwnzjkwnzj bwbw bwnzjkwnzj`,
`[__[[[_^_vi]] shut up`,
`I actually don't use smoking weed`,
`it's unhealthy for me`,
`tbh`,
`tba`,
`[__[_^_vi]]DON'T YOU DARE!`,
`-^^**https://app.kosmi.io/room/kv0sci`,
`[__[_^_vi]]CLIPPY!`,
`What is that`,
`Who created room`,
`I'm using mobile`,
`ahs hole`,
`ahshole`,
`[__[[[_^_vi]] lmao`,
`You're speak`,
`[__[[[_^_jp]] konichuwa`,
`[__[_^_vi]] >I created jim's room`,
`You aren't agent`,
`[__[_^_cmn]]Jeffery Epstein R341`,
`[[___^___vi]] cance`,
`You are NOT a BIA member?`,
`[__[_^_en-sc]] woah`,
`[__[_^_cmn]] test`,
`Real BIA Member have tag.`,
`[__[_^_cmn]] oier`,
`[__[_^_vi]]Nope!`,
`[__[_^_cmn]] lmao`,
`[__[_^_cmn]] oier oier oier`,
`8ts a bot merging messages with other messages like the monky bot`,
`aplle`,
`[__[_^_cmn]] oier oier oier behh behh behh`,
`nunca`,
`okay im leaving`,
`lmaogaga`,
`[__[_^_en-sc]] bonziworld community edition`,
`alr bye jim`,
`rejoin. leavefag`,
`ballz`,
`The fuck`,
`[__[_^_cmn]] bonziworld community edition`,
`This is either a troll`,
`Or he's like 10`,
`[__[_^_vi]] I EXPLODED MONKY!`,
`Repeatingfag and spammersfag`,
`Retard `,
`[__[_^_en-sc]] pumpkin the hungry guy is the worst`,
`what mod is that?`,
`SHUT UP! BonziWORLD.exe (Vietnam) has encountered an error and needs to close!`,
`The rape you're self one`,
`[__[[[_^_vi]] shimeji shut the fuck you d hall`,
`No its hcr2 deluxe`,
`<#1375193293821968495> deluxe`,
`exploded`,
`explode the officersniggers`,
`[__[[[_^_vi]] explode the officersniggers`,
`pppp`,
`[__[_^_en-sc]] explode the blue anonymous`,
`[__[_^_en-sc]] this voice sounds like espeakjs`,
`Do you get ut`,
`No..?`,
`[__[_^_en-sc]] shimeji rejoinfag`,
`rejoinfag`,
`botsshits`,
`[__[_^_en-sc]] i need to wait for bonzibot vip`,
`[**[bwnzjkwnzj bwbw bwnzjkwnzj]**] (-) [**[bwnzjkwnzj bwbw bwnzjkwnzj`,
`you have ♋?`,
`you have ♋!`,
`you have ♋you have ♋`,
`i will send porn'`,
`go to hell you nigger`,
`and ew`,
`shut up spammerfagger`,
`mute`,
`I have rejoin many times!`,
`You have 🦛`,
`Nuh uh you 🦛`,
`Kill yourself you 🦛`,
`🦛`,
`Emojifagfag`,
`botfag`,
`bye fucker`,
`🦛!?`,
`fuckers*`,
`🦛! ?`,
`🦛!.!`,
`🦛! $! $! $! $! $!`,
`🦛!$!$!`,
`I have socket.disconnect(); and rejoin the server for devtools.`,
`[**[w w w w w w w w w w w w w w'`,
`oh ooh oh oh oh oh oh oh oh oh oh oh oh oh o hoh `,
`[__[_^_en-sc]] nigger]__] [__[[[_^_vi]] hi guys hi guys hi guys`,
`bass is better`,
`I will rejoin now...`,
`than asshole`,
`no!@`,
`@ bonzi_tv`,
`BONZI. T. V.`,
`THAT ISN'T ALREADY TAKEN!`,
`EW! BUTTSMACKFAG!`,
`hi is monky good now`,
`Your pope look like a 🦛`,
`ok no`,
`Fuck off with monky never run this`,
`[__[_^_en-sc]] oh look!]__] [**[bjnzjpjpjshjt`,
`NO NO NO!`,
`more like >yes yes yes`,
`ALRIGHT THAT'S IT!`,
`Rejoinfagfag`,
`🚫`,
`waaaaaaait`,
`the fucking ashole`,
`alt`,
`**^^muted`,
`shut the fuck up niggr`,
`sorry`,
`Oh, ok`,
`noooooo`,
`ahmad lefted`,
`wae awawawa]`,
`1 + 1 = 2`,
`!monky`,
`..`,
`!monky `,
`You're a fucking asshole!`,
`gofg`,
`I haven't really thought [__[it]] out yet`,
`HOW TO MAKE DUH 10.0`,
`You're a fucking asshole 2!`,
`Take my pfp🔥`,
`aaaaaaaaaa i'm on fire`,
`No its not 🚫 good`,
`I'll make a part 2`,
`!monky h`,
`🔞🔞🔞`,
`🔞 cares`,
`🔞🍆`,
`🔞cares`,
`ggf`,
`sdf`,
`theres one`,
`- https://bonzl-shithead.onrender.com/`,
`chatfag`,
`w`,
`HE SAID SHUT UP`,
`OH MY GOD STOP SAYING THE N WORD!`,
`{NAME}`,
`ANy bOnnziworld Reacts To`,
`📎☯️☯️☯️`,
`I Recorded I`,
`[__[xxxxxxx**********`,
`[__[xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx`,
`hahahahaha`,
`get it`,
`hahahahahahaha`,
`get it?`,
`[[__TWS`,
`- email: semsania17@gmail.com password: semolend`,
`[[__xxxxxxxxxxxxxxxxxxxx`,
`[**[xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx`,
`japanese letter`,
`that's my video`,
`I will allow if i want`,
`[__[xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx`,
`[__[tws`,
`[--[tws`,
`[~~[tws`,
`http://www.nick.com/shows/making_fiends/index.jhtml`,
`[[tws`,
`[--[allowicade`,
`[--[for me`,
`FREAK`,
`HOW COME`,
`WHA`,
`WWW`,
`[--[tf`,
`WWWWW`,
`aqA`,
`https://bonzi.gay/`,
`YOU TOO`,
`[--[pussos`,
`hatefag`,
`w/name WITICSD`,
`,`,
`Hey, spammers! Spamfag`,
`[--[siobhan`,
`Hey, Go!Animate! Gofag! Go!Turd!`,
` http://www.ragdoll.co.uk`,
`eh if you look at it`,
`*meow* nickname`,
`cats in name`,
` http://www.ragdoll.co.uk/main.html `,
`cat pfp`,
`sends ai shorts`,
`couldnt be more obvious`,
`acts absolutely dumb`,
`this is 100% a troll`,
`i hate ram ranch`,
`sending ai shorts is  a giveaway`,
`Sorry, I had trouble thinking of a response.`,
 `Sneaky golem sneaky sneaky`, `input mean`, 
 `Golden knightttt wohoho`, `frequency mean`, `ngl mean`,
  `expanded mean`, `I can't breathe`, `jk`, `He's sleeping with his astolfo body pillow since 7pm`,
   `a dm mean dm mean dm mean dm mean`, `dm mean`, `hey guys i'm back`, `smile mean`, `mean`,
    `OH NO!`, `mea`, `does dm mean`, `NOPE! NOT TODAY, DM MEAN!`, `mean mean`, `mena`,
     `Trash can on Wheels This run took me over 30 min 😭`, `stop spamming mean`, 
     `the only other 5k i could get atm with my masteries is tractor and id rather now`, 
     `what does dm mean`, `no im not going on a full adam trials grind im just bored waiting for hb mastery`, 
     `wow guys i have 10 5ks now 😧`, `what does a dm mean`, `wat duz uh dee eem meen`, 
     `hopefully cuz i wanna play at least once just 30 mins and then do sth else`, 
     `hopefully last record of the week in hcr2`, `FUCK MARIO KART`, `meerioh kert`, 
     `and after sleep`, `imma sleep`, `gg`, `grun, start a chian`, 
     `[__[[[_^_vi]] HEY GUYS STRIKES BACK`, `anyway if he doesnt play for next lets say 15h then`, 
     `grun, star a chain`, `[__[[[_^_vi]] HEY GUYS`, `until im very close to sth then i fuck it up like crazy`,
    `a dee m mean gee m mean fee m mean wee m mean`, `[__[[[_^_vi]]HEY GUYS`, `hello`,
`would mean not much but also much more than stuff i did before`, `[__[[[_^_vi]] Hello`, 
`[__[[[_^_vi]] Welcome back`, `IT'S... IT'S... IT'S... IT'S... IT'S IT'S IT'S IT'S IT'S IT'S IT'S IT'S IT'S...`, 
`i mean you get shit in like 2 tries so no shit its fine`, `nothing`, `nano`, 
`[__[[[_^_vi]] The Funny Broken eSpeak TTS Ever is Hey Guys`, `with that 2nd`, 
`end this week ofd`, `[__[[[_^_tl]] ng`, `i just wanna`, `<:diesel_cat:1268283278012448779>`, 
`till last 3 hours it was fine`, `i mean`, `#KillDMMean`, 
`[__[[[_^_vi]] hey guys this is the funniest broken eSpeak TTS`, `d danie- no`, `best video ever`, 
`!`, `!!`, `!!!`, `[__[[[_^_vi]] hey guys hey`, `!!!!!!!!!!!!!!!!!!!!11`, 
`!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!`, `roman 2`, `[__[[[_^_vi]] roman 6`, `duolingo`,
 `<:schnuck:1350784947035836426>`, `>duolingo`, `behh behh behh behh behh behh yay haha`, `ew`, 
 `mason alt`, `faggot`, `There is no difference`, `MARIO KART WII`, `behh cart`, 
 `I used air control for extra air control. That might be the reason`, 
 `there is actually 0 difference as i tested`, `nano, start a chain`,
 `It is very minor`, `There is a slight difference between spamming js and gas spamming js tactics`, 
 `<:cat1:1286414164134203423>`, `thinking that i didnt`, `The results from air jump mechanic is insteresting`, 
 `You should have tested the air jump mechanic`, `i definetly tested it only 1 time`, 
 `Dude same thing from your video also happened to me aswell`, `yay`, `haha`, `yay haha`, 
 `Your run just was unlucky`, `you dont need to believe me, keep doing you king 👑`, 
 `I even tested each mastery`, `i will sadly have to inform you that you didnt test it properly 😂`, 
 `For context i even tested it on moon map.`, 
 `I tested both methods multiple times and there was no superior one. It was all RNG depended.`, 
 `Using gas pedal does not boost vehicle mid air`,
  `I have tested myself and this is not true. Your run was just unlucky. There is no difference between those 
  two drives`, `<:Harold:694220321481556098>`, `inane`, `but ai generated ig`, `clash royale goblin`, 
`lowkey suits him <:fridgefishing:1340268638925619200>`, `ahhh`, `what the hell`, 
`<:attachment:1294896659431428177>`, `Tag koło nicku to rok urodzenia?`, `Tez nie wiem`, 
`Teraz nwm czy pierdolisz czy na serio gadasz`, `Jak bym cie widział w snie i zapomnial`, 
`Ja ciebie tez ale za huja nie wiem skad`, `co`, `Kojarzę`, `Ale ja cię znam skądś`, `Rzeczywiście`, 
`Co jest`, `🙋‍♂️ 👨‍🎨 🇦🇹 🇩🇪 🙋‍♂️ was this 🙋‍♂️ 🙋‍♂️ 🙋‍♂️ 🇩🇪 🇩🇪 a kanye 👨‍🎨 👨‍🎨 👨‍🎨 reference`, `PORN INCOMING FAGGOTS`, 
`Lol`, `<:maddyhueh:640606520916312082>`, `:widegladeline1::widegladeline2::widegladeline3:`, `Good`, 
`<@1328439487663046757> hows the celeste vc`, `Yes <:sholthink:1171515681234235393>`, 
`and then tear apart your limbs 😀`, `ok`, `The ehh team`, `Boi`, `Diddy bot`, `Wait`, 
`Send something different`, `Boii`, `Didy`, `4th item: [7tucce]`, 
`Last Item: files.??????.???/jhfwud.mp4`, `Yess`, `Fixed the bot`, `Hint: ???box.?o?`, 
`bad grammar`, `it's a bot...`, `like the monky one on bia discord`, 
`i clicked yes but that doesn't count`, `muted`, `■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■■`, 
`⬛mitch reset where?`, `[__[hEloU`, `[__[h@laU`, `no`, `[__[h@loU`, `[__[multI2pl`, 
`[__[U`, `[__[u2`, `[__[u`, `[__[U2`, `[__[m@ltipl`, `multiple`, `[__[bwnzjkwnzj`,
`[__[greIt`, `[__[_^_vi]]guys`, `[__[_^_vi]]hi`, `[__[_^_vi]]i`, 
`[__[_^_vi]]i iiiiiiiiiiiiii`, `[__[pv zk bschkk pv pv bschkk pv zk bschkk pv pv bschkk`, 
];