[
    ">downloaed citureis to wpalay gnnt4endo 3ds gawmeas on youer pee see  pee pee",
    "No",
    "me:",
    "ew",
    "forced download virus user alert",
    "Bitch",
    "[__[_^_cmn deIdi:l",
    "Es",
    "©️, ®️, ™️",
    "[__[_^_vi t'@:2j_| J^'a:1N_| n'o4_|",
    "DanielVIRUS",
    "[__[deIdi:l",
    "[__[_^_vi t'@:2j_| J^'a:1N_| n'o4_|",
    "™️",
    "*force download virus user alert",
    "Daniel(something else)fag",
    "Daniel(something else)fag",
    "Daniel(something else)fag",
    "Daniel(something else)fag",
    "Daniel(something else)fag",
    "™️",
    "",
    "[__[_^_vi t'@:2j_| J^'a:1N_| n'o4_|",
    "[__[deIdi:c",
    "TRADEMARK",
    "[__[_^_vi t'@:2j_| J^'a:1N_| n'o4_|",
    "[__[_^_vi-hue NO:",
    "™️",
    "[__[_^_vi-hue ol/",
    "[__[_^_vi t'@:2j_| J^'a:1N_| n'o4_|",
    "[__[_^_vi-hue o",
    "stop making up lies about me tristan.",
    "*gasp* virusfag alert :0",
    "[__[_^_vi-hue O",
    "[__[_^_vi-hue O",
    "or else.",
    "DanielVIRUS",
    ":>",
    "©️®️",
    "[__[_^_vi-hue u-",
    "[__[_^_vi-hue ban",
    "or else wut?",
    "[__[_^_vi-hue a:",
    "[__[_^_vi O",
    "DanielVIRUS",
    "[__[_^_vi N",
    "[__[_^_vi Nl",
    "[__[_^_vi pN",
    "[__[_^_vi cN",
    "[__[deIdi:l i:s a bi:c????????dZVstkIdIN",
    "[__[_^_vi tSN",
    "DanielVIRUS is a malware virus",
    "[__[_^_vi tSLN",
    "[__[_^_vi x,o#1N_| k'O3_| v'u6_| n'o4_|",
    "Daniel(something else)fag",
    "oh no",
    "Daniel(something else)fag",
    "Daniel(something else)fag",
    "[__[_^_vi baN",
    "nvm",
    "[__[_^_vi x,o#1N_| k'O3_| v'u6_| n'o4_|",
    "E. A. Sports it's in the game",
    "[__[deIdi:l i:s a bi:c????????????????????????????????????????dZVstkIdIN",
    "[__[_^_vi ba:N",
    "[__[deIdi:l i:s a bi:c????????????????????????????????????????dZVstkIdIN",
    "[__[_^_vi b,a:N",
    "DanielVIRUS",
    "[__[deIdi:l i:s a bi:c????????????????????????????????????????dZVstkIdIN",
    "[__[deIdi:l i:s a bi:c????????????????????????????????????????dZVstkIdIN",
    "E. A. Sports It's in the game",
    "Hey jewa",
    "[__[deIdi:l i:s a bi:c????????????????????????????????????????dZVstkIdIN",
    "big bang",
    "[__[deIdi:l i:s a bi:c????????????????????????????????????????dZVstkIdIN",
    "[__[deIdi:l i:s a bi:c????????????????????????????????????????dZVstkIdIN",
    "Wake up",
    "DanielVIRUS",
    ".",
    "lle",
    "behh",
    "lle",
    "unlike kiddie invasion",
    "lles",
    "DanielVIRUS",
    "[__[_^_vi b,a:N",
    "DanielVIRUS",
    "[__[llllllllllll",
    "DanielVIRUS",
    "[__[_^_vi b,a:?aN",
    "[__[_^_vi b,a:?N",
    "[__[_^_vi b,a:?N",
    "yo.  It’s ya boi Harley in da house.   What’s goody what’s goody what’s goody?   wanna give a special shout out to da big homie John.  Always keepin me fed n shit.   thought I’d just come up here, kick it, eat bugs and chill.  Figured since I just got dis dope ass new aquarium…might as well rock the swag to go wit it boyz.",
    "[__[_^_vi b,a::",
    "[__[lllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll",
    "[__[llllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll",
    "yo.  It’s ya boi Harley in da house.   What’s goody what’s goody what’s goody?   wanna give a special shout out to da big homie John.  Always keepin me fed n shit.   thought I’d just come up here, kick it, eat bugs and chill.  Figured since I just got dis dope ass new aquarium…might as well rock the swag to go wit it boyz.",
    "[__[lllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll",
    "[__[lllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll",
    "[__[_^_vi x,o#1N_| k'O3_| v'u6_| n'o4_|",
    "yo.  It’s ya boi Harley in da house.   What’s goody what’s goody what’s goody?   wanna give a special shout out to da big homie John.  Always keepin me fed n shit.   thought I’d just come up here, kick it, eat bugs and chill.  Figured since I just got dis dope ass new aquarium…might as well rock the swag to go wit it boyz.",
    "Going to test it now",
    "WAIT",
    "OH NO",
    "Daniel(something else)fagDaniel(something else)fag",
    "Daniel(something else)fag",
    "Daniel(something else)fag",
    "Daniel(something else)fagDaniel(something else)fag",
    "Daniel(something else)fag",
    "[__[_^_vi n'O3_| c'i4_| d_'u@2_| t'o7j_|",
    ">nusoi",
    "kek",
    "[__[lllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllllll",
    "[__[_^_vi n'O3_| c'i4_| d_'u@2_| t'o7j_|",
    "all right fine",
    "[__[glllllllllllllllllllllllllllllllllllllllllllllllllllllllllll",
    "DanielALIVE",
    "DanielALIVE",
    "lle",
    "ok",
    "DanielALIVE",
    ":(",
    "Kys nigger",
    "i get it",
    ":",
    "DanielALIVE",
    "Niggger jarty ppedo faggot",
    "{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{{",
    "[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[",
    "oh my god the high heels are alive",
    "unlike Daniel(word)",
    "]]]]]]]]]]]]]]]]]]]]]]]][[[[[[[[[[[[[[][][][][]]]][][][][",
    "DanielALIVE",
    "[][][][]][][][][][]nigger99923564647835",
    ".",
    "daniel [__[_^_vi d_,a:5_| c'e3kh_|",
    "daniel [__[_^_vi d_,a:5_| c'e3kh_|",
    "daniel [__[_^_vi d_,a:5_| c'e3kh_|",
    "WAIT",
    "OH NO",
    "DanielHTML",
    "nigger below mi",
    "daniel [__[_^_vi d_,a:5_| c'e3kh_|",
    "nigger",
    "DanielHTML",
    "nigger",
    "nigger",
    "daniel [__[_^_vi d_,a:5_| c'e3kh_|",
    "nigger",
    "ew",
    "g\\erfh",
    "racist",
    "bud",
    "DanielHTML",
    "daniel [__[_^_vi d_,a:5_| c'e3kh_|",
    "DanielHTML",
    "faggot kike jartypedojartytroon",
    "daniel [__[_^_vi d_,a:5_| c'e3kh_|",
    "DanielSLEEPING",
    "daniel [__[_^_vi d_,a:5_| c'e3kh_|",
    "STOP",
    "DanielHTM",
    "STOP",
    "STPO",
    "PSPTO",
    "stop ranting me tacwiatcmaictaictaictawitcwiatciwtciawctmiwtooototototmtomomomomtocmtomtototototo",
    "kys negroid",
    "DanielHTML",
    "jarty cuck slutta",
    "WAI",
    "DGNOEABNOBRAPM",
    "jarty",
    "N",
    "WAIT",
    "daniel [__[_^_vi d_,a:5_| c'e3kh_|",
    "jarty",
    "NO",
    "nigger",
    "daniel [__[_^_vi d_,a:5_| c'e3kh_|",
    "KHF",
    "'GK",
    "esl fnf pedo nigger",
    "DanielHTML",
    "THAT'S IT",
    "DanielHTML DanielHTML",
    "daniel [__[_^_vi d_,a:5_| c'e3kh_|",
    "daniel [__[_^_vi d_,a:5_| c'e3kh_|",
    "beals deals eels feels heals keels kneels meals peals peels reales reals reels seals shiels squeals steals steels wheels ceils creels skeels teals veals weals wheals ciels deils diels geals jeels jheels riels seels speels spiels streels sweals tweels weels zeals",
    "DanielLEFT",
    "welp",
    "daniel [__[_^_vi d_,a:5_| c'e3kh_|",
    "he rag3d",
    "leet speak :0",
    "Daniel(X)fags",
    ".",
    "DanielHTML",
    "[__[_^_vi 'e-1n^_| '@I3_| z.'@:2j_| d_'i7_|",
    "[__[_^_vi 'e-1n^_| '@I3_| z.'@:2j_| d_'i7_|",
    "Daniel(X)fags",
    "WAIT",
    "OH NO",
    "DanielCAMEL",
    "[__[_^_vi 'e-1n^_| '@I3_| z.'@:2j_| d_'i7_|",
    "ew",
    "DanielCAMEL",
    "[__[_^_vi 'e-1n^_| '@I3_| z.'@:2j_| d_'i7_|",
    "fcu",
    "fuc",
    "DanielCAMEL",
    "[__[_^_vi 'e-1n^_| '@I3_| z.'@:2j_| d_'i7_|",
    "what",
    "the",
    "[__[_^_vi 'e-1n^_| '@I3_| z.'@:2j_| d_'i7_|",
    "fuck",
    "DanielCAMEL",
    "[__[_^_vi 'e-1n^_| '@I3_| z.'@:2j_| d_'i7_|",
    "daniel(x)fags",
    "[__[_^_vi 'e-1n^_| '@I3_| z.'@:2j_| d_'i7_|",
    "camel",
    "[__[_^_vi 'e-1n^_| '@I3_| z.'@:2j_| d_'i7_|",
    "DanielCAMEL",
    "[__[_^_vi 'e-1n^_| '@I3_| z.'@:2j_| d_'i7_|",
    "STOP CALLING ME THAT",
    "[__[_^_vi 'e-1n^_| '@I3_| z.'@:2j_| d_'i7_|",
    "[__[_^_vi 'e-1n^_| '@I3_| z.'@:2j_| d_'i7_|",
    "all right fine",
    "DanielALIVE",
    "ew",
    "gorefag",
    "12345",
    "vorecuck bud",
    "gorefag",
    "vorefag",
    "gorefag",
    "*gorecuck bud",
    "obsessed nigger says gorefag",
    "faggot",
    "gorefag",
    "obsessed",
    "gorefag",
    "faggot",
    "suck my tbp",
    "also racist",
    "faggot",
    "dead nigger baby",
    "jews raper alt",
    "Gorefag",
    "Child gore is ILLEGAL",
    "racist!",
    "WAIT",
    "OH NO",
    "danielCAMEL",
    "danielCAMEL",
    "STOP",
    "pornfag!",
    "danielCAMEL",
    "CALLING",
    "ME",
    "THINGS",
    "OR",
    "ELSE",
    "I",
    "pornfag! gofag! gorefag! vorefag!",
    "WILL",
    "MUTE",
    "YOU",
    "baboon dick",
    "or else wut?",
    "OK>",
    "MUTE",
    "ok",
    ":(",
    "DanielSTOPCALLINGMETHINGSORELSEIWILLMUTEYOU",
    "bag leak speak cheek sneak streak freak meek sleek weak peak shriek squeak geek tweak bleak peek reek beak greek steek week creak slick thick wreak gleek chic leek creek eek keek tweek wheek cleek fleek streek teak deek neek queek teek beek bleek crick deke mcpeek phreak sheek sneek eke klick kriek reak tweag yeek zig fleak riek siek beag freke keech klieg liek mcpeak peag dreich fiqh grieg meak nic peke schtik seke shtik sieg speke stieg txtspeak leag league mick",
    ".",
    ">Why can't I get good femboy porn without it being some fucking race play wall of text boot kicker bs. NO IM NOT GOING TO REPRODUCE WITH THE GORILLA SPAWN. The whole bbc bull raisin is beyond retarded in the sense of \"omg baboon penis is sometimes big that somehow makes them the superior life form\" if they're the superior life form then why are they still living in fucking mud huts and banging theirs cousins",
    "bag faek leak speak cheek sneak streak freak meek sleek weak peak shriek squeak geek tweak bleak peek reek beak greek steek week creak slick thick wreak gleek chic leek creek eek keek tweek wheek cleek fleek streek teak deek neek queek teek beek bleek crick deke mcpeek phreak sheek sneek eke klick kriek reak tweag yeek zig fleak riek siek beag freke keech klieg liek mcpeak peag dreich fiqh grieg meak nic peke schtik seke shtik sieg speke stieg txtspeak leag league mick",
    "I hate pornfag",
    "DanielALIVE",
    "i love baboon dick",
    "in my booty hole",
    "suck my baboon dick",
    "baboon dick",
    "nigger shut up faggot",
    "jews",
    "baboon dick",
    "baboon penis",
    "nigger penis",
    "kys coalyma pedotroon",
    "WAIT",
    "OH NO",
    "danielCAMEL",
    "NOOOOOOOO",
    "THAT'S IT",
    "[__[_^_vi t'@:2j_| J^'a:1N_| n'o4_| v,i2_| 'e-1n^_| '@I3_| l,a:2_| Q'O1z.E1_|",
    "danielniggerjewkike95432958396823868288628527534785782358",
    "DONE",
    "498582368236",
    "NOOOOO",
    "danielCAMEL",
    "damn",
    "you really muted us all",
    "danielCAMEL",
    "danielCAMEL",
    "he left",
    "lmao",
    "DanielAMERICA",
    "HEY",
    "hey dan can you hear or see my messages",
    "danielCAMEL",
    "YES",
    "danielCAMEL",
    "oh ok",
    "i am nigger poop",
    "danielCAMEL",
    "i thought you muted me",
    "$r$ AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA",
    "DanielYES",
    "nigger poop",
    "nigger poop",
    "nigger poop",
    "danielCAMEL danielCAMEL",
    "nigger poop",
    "NIGGA SHIT",
    "CAMEL?",
    "danielCAMEL",
    "DanielAMERICA DanielAMERICA",
    "ew",
    "Daniel(X)fag",
    "dayd",
    "daid",
    "nigger poop",
    "dade",
    "nigger poop",
    "babe",
    "danielCAMEL",
    "danielCAMEL",
    "oh wait-",
    "danielCAMEL",
    ".",
    "dade",
    ".",
    "dan triple i",
    "The Gassiest Poop Poop Mouse Yet",
    "The Gassiest Poop Poop Mouse Yet",
    "I SEE YOU DAMNIEL",
    "ew",
    "seefag",
    "kys",
    "a b see",
    "Nigger poop",
    "danielCAMEL",
    "aye bee see",
    "Danii marry kys",
    "danielCAMEL",
    "danielCAMEL",
    "danielCAMEL",
    "Nigger poop",
    "IT'S A GASSY WARRIOR",
    "Nigger poop",
    "Kysiio",
    "Nigger poop",
    "The Gassiest Poop Poop Mouse Yet The Gassiest Poop Poop Mouse Yet The Gassiest Poop Poop Mouse Yet The Gassiest Poop Poop Mouse Yet The Gassiest Poop Poop Mouse Yet The Gassiest Poop Poop Mouse Yet The Gassiest Poop Poop Mouse Yet The Gassiest Poop Poop Mouse Yet The Gassiest Poop Poop Mouse Yet The Gassiest Poop Poop Mouse Yet The Gassiest Poop Poop Mouse Yet The Gassiest Poop Poop Mouse Yet The Gassiest Poop Poop Mouse Yet The Gassiest Poop Poop Mouse Yet The Gassiest Poop Poop Mouse Yet The Gassiest Poop Poop Mouse Yet The Gassiest Poop Poop Mouse Yet The Gassiest Poop Poop Mouse Yet",
    "danielCAMEL",
    "My clitty is leaking",
    "O algo",
    "My clitty is leaking",
    "the fuck is even a clitty",
    ".",
    "Hi",
    "Hi",
    "oh wait",
    "hi",
    "clit",
    "Clitty is my tiny white pecker",
    "Hi",
    "Hi",
    "Danii well you marry kys",
    "Hi",
    "Hi",
    "Hi",
    "Hi",
    "Im hitting my balls for black bulls",
    "goanimate",
    "oh look",
    "dadidl",
    "ew",
    "I will send porn",
    "dadielfag",
    "[__[dani:c",
    "Black bvlls rape my booty hole",
    "kys you dick",
    "GOANIMATE",
    "Dp it",
    "[__[deIdi:c",
    "I will send porn",
    "Baboon dick in my tiny white boy hole",
    "[__[deIdi:c",
    "[__[deIdi:c",
    "I will send cp",
    "pornfag, gofag",
    "EW",
    "Do it hellnigger",
    "pornfag",
    "gofag",
    "[[__lele",
    "Ok",
    "goanimate",
    "send cp i deleted my stash yesterdaay",
    "d daniel,",
    "d daniel, d daniel, d daniel, d daniel,",
    "I will do that",
    "d daniel, d daniel, d daniel, d daniel, d daniel, d daniel, d daniel, d daniel, d daniel, d daniel,",
    "[__[Chuck e Cheese",
    "d daniel, d daniel, d daniel, d daniel, d daniel, d daniel, d daniel, d daniel, d daniel, d daniel, d daniel,",
    "WAIT",
    "[__[deIdi:c",
    "I will send co",
    "Do you have a good stash xister",
    "[__[deIdi:c",
    "YOU CAN BYPASS?",
    "[__[deIdi:c",
    "[__[Chuck e Cheese",
    "[__[Chuck e Cheese",
    "[__[Chuck e Cheese",
    "[__[Chuck e Cheese",
    "[__[deIdi:c",
    "Hellnigger post cp",
    "[__[deIdi:c",
    "",
    "dahiel",
    "[__[_^_cmn t'A35_| S;i55'@r214_|",
    "DanielRETRO",
    "explode despicable me",
    "[__[_^_vi t'@:2j_| J^'a:1N_| n'o4_|",
    "©️, ®️, ™️.",
    "[__[_^_cmn '@r214_|",
    "©️®️™️",
    "[__[_^_cmn a",
    "WAIT",
    "OH NO",
    "DanielINFECTED",
    "DanielINFECTED",
    "[__[_^_cmn danielded",
    "You"
]